DROP TABLE IF EXISTS sentence_classes;
DROP TABLE IF EXISTS sentence_partials;

CREATE TABLE sentence_classes (
  id VARCHAR(255),
  next VARCHAR(255)
);

CREATE TABLE sentence_partials (
  id INT,
  value TEXT,
  class VARCHAR(255)
);

INSERT INTO sentence_classes (id, next) VALUES
("LieuMas", "AdjMas"),
("AdjMas", "QuaMas"),
("QuaMas", "NomMas")
;

INSERT INTO sentence_partials (value, class) VALUES
("Ecueil", "LieuMas"),
("Bourg", "LieuMas"),
("Castel", "LieuMas"),
("Champ", "LieuMas"),
("Château", "LieuMas"),
("Fond", "LieuMas"),
("Mont", "LieuMas"),
("Moulin", "LieuMas"),
("Pont", "LieuMas"),
("Port", "LieuMas"),
("Pré", "LieuMas"),
("Pic", "LieuMas"),
("Puy", "LieuMas"),
("Roc", "LieuMas"),
("Rocher", "LieuMas"),
("Tertre", "LieuMas"),
("Val", "LieuMas"),
("Valon", "LieuMas"),
("Lac", "LieuMas"),
("Bois", "LieuMas"),
("Bord", "LieuMas"),
("Cerf", "LieuMas"),
("Croc", "LieuMas"),
("Comble", "LieuMas"),

("Roche", "LieuFem"),
("Ville", "LieuFem"),
("Eau", "LieuFem"),
("Vigne", "LieuFem"),
("Terre", "LieuFem"),
("Forge", "LieuFem"),
("Maison", "LieuFem"),
("Mer", "LieuFem"),
("Rive", "LieuFem"),
("Roche", "LieuFem"),
("Ronce", "LieuFem"),
("Cime", "LieuFem"),
("Herbe", "LieuFem"),
("Citadelle", "LieuFem"),
("Passerelle", "LieuFem"),
("Butte", "LieuFem"),
("Colline", "LieuFem"),
("Brume", "LieuFem"),
("Cour", "LieuFem"),
("Douve", "LieuFem"),
("Dune", "LieuFem"),
("Fosse", "LieuFem"),
("Grange", "LieuFem"),
("Muraille", "LieuFem"),
("Plaine", "LieuFem"),
("Tour", "LieuFem"),
("Valée", "LieuFem"),

("vif", "AdjMas"),
("rude", "AdjMas"),
("vert", "AdjMas"),
("vieu", "AdjMas"),
("bas", "AdjMas"),
("beau", "AdjMas"),
("blanc", "AdjMas"),
("clair", "AdjMas"),
("fier", "AdjMas"),
("franc", "AdjMas"),
("froid", "AdjMas"),
("grand", "AdjMas"),
("haut", "AdjMas"),
("morne", "AdjMas"),
("mort", "AdjMas"),
("noble", "AdjMas"),
("noir", "AdjMas"),
("fou", "AdjMas"),
("court", "AdjMas"),
("-sur-mine", "AdjMas"),
("-sur-lac", "AdjMas"),
(" du tonnerre", "AdjMas"),
("-à-brume", "AdjMas"),
("-à-embrum", "AdjMas"),
("-à-fer", "AdjMas"),
("-à-loup", "AdjMas"),
("-à-pluie", "AdjMas"),
("brave", "AdjMas"),
("calme", "AdjMas"),
("courbe", "AdjMas"),
("-de-fer", "AdjMas"),
("-de-feu", "AdjMas"),
("-de-mine", "AdjMas"),
("-de-père", "AdjMas"),
("-de-pluie", "AdjMas"),
("-de-suif", "AdjMas"),
("doré", "AdjMas"),
("droit", "AdjMas"),
("dur", "AdjMas"),
("-en-bois", "AdjMas"),
("-en-croc", "AdjMas"),
("-en-embrum", "AdjMas"),
("-en-fer", "AdjMas"),
("-en-feu", "AdjMas"),
("-en-ours", "AdjMas"),
("-en-père", "AdjMas"),
("-en-suif", "AdjMas"),
("fer", "AdjMas"),
("long", "AdjMas"),
("neuf", "AdjMas"),
("-sous-cerf", "AdjMas"),
("-sous-croc", "AdjMas"),
("-sous-écume", "AdjMas"),
("-sous-lin", "AdjMas"),
("-sous-loup", "AdjMas"),
("-sous-puit", "AdjMas"),
("-sous-suif", "AdjMas"),
("-sous-bois", "AdjMas"),
("-sous-embrum", "AdjMas"),
("-sous-laine", "AdjMas"),
("-sous-pluie", "AdjMas"),
("-sous-tourbe", "AdjMas"),
("-sur-suif", "AdjMas"),
("-sur-puit", "AdjMas"),
("-sur-loup", "AdjMas"),
("-sur-bois", "AdjMas"),
("-sur-cerf", "AdjMas"),
("-sur-croc", "AdjMas"),
("-sur-écume", "AdjMas"),
("-sur-embrum", "AdjMas"),
("-sur-lin", "AdjMas"),
("-sur-laine", "AdjMas"),
("-sur-pluie", "AdjMas"),
("-sur-tourbe", "AdjMas"),
("royal", "AdjMas"),

("vive", "AdjFem"),
("rude", "AdjFem"),
("verte", "AdjFem"),
("vieille", "AdjFem"),
("basse", "AdjFem"),
("belle", "AdjFem"),
("blanche", "AdjFem"),
("claire", "AdjFem"),
("fière", "AdjFem"),
("franche", "AdjFem"),
("froide", "AdjFem"),
("grande", "AdjFem"),
("haute", "AdjFem"),
("morne", "AdjFem"),
("mort", "AdjFem"),
("noble", "AdjFem"),
("noire", "AdjFem"),
("folle", "AdjFem"),
("courte", "AdjFem"),
("-sur-mine", "AdjFem"),
("-sur-lac", "AdjFem"),
(" du tonnerre", "AdjFem"),
("-à-brume", "AdjFem"),
("-à-embrum", "AdjFem"),
("-à-fer", "AdjFem"),
("-à-loup", "AdjFem"),
("-à-pluie", "AdjFem"),
("brave", "AdjFem"),
("calme", "AdjFem"),
("courbe", "AdjFem"),
("-de-fer", "AdjFem"),
("-de-feu", "AdjFem"),
("-de-mine", "AdjFem"),
("-de-père", "AdjFem"),
("-de-pluie", "AdjFem"),
("-de-suif", "AdjFem"),
("dorée", "AdjFem"),
("droite", "AdjFem"),
("dure", "AdjFem"),
("-en-bois", "AdjFem"),
("-en-croc", "AdjFem"),
("-en-embrum", "AdjFem"),
("-en-fer", "AdjFem"),
("-en-feu", "AdjFem"),
("-en-ours", "AdjFem"),
("-en-père", "AdjFem"),
("-en-suif", "AdjFem"),
("fer", "AdjFem"),
("longue", "AdjFem"),
("neuve", "AdjFem"),
("-sous-cerf", "AdjFem"),
("-sous-croc", "AdjFem"),
("-sous-écume", "AdjFem"),
("-sous-lin", "AdjFem"),
("-sous-loup", "AdjFem"),
("-sous-puit", "AdjFem"),
("-sous-suif", "AdjFem"),
("-sous-bois", "AdjFem"),
("-sous-embrum", "AdjFem"),
("-sous-laine", "AdjFem"),
("-sous-pluie", "AdjFem"),
("-sous-tourbe", "AdjFem"),
("-sur-suif", "AdjFem"),
("-sur-puit", "AdjFem"),
("-sur-loup", "AdjFem"),
("-sur-bois", "AdjFem"),
("-sur-cerf", "AdjFem"),
("-sur-croc", "AdjFem"),
("-sur-écume", "AdjFem"),
("-sur-embrum", "AdjFem"),
("-sur-lin", "AdjFem"),
("-sur-laine", "AdjFem"),
("-sur-pluie", "AdjFem"),
("-sur-tourbe", "AdjFem"),
("royale", "AdjFem"),

("Vif", "QuaMas"),
("Rude", "QuaMas"),
("Vert", "QuaMas"),
("Vieu", "QuaMas"),
("Bas", "QuaMas"),
("Beau", "QuaMas"),
("Blanc", "QuaMas"),
("Clair", "QuaMas"),
("Fier", "QuaMas"),
("Franc", "QuaMas"),
("Froid", "QuaMas"),
("Grand", "QuaMas"),
("Haut", "QuaMas"),
("Morne", "QuaMas"),
("Mort", "QuaMas"),
("Noble", "QuaMas"),
("Noir", "QuaMas"),
("Fou", "QuaMas"),
("Court", "QuaMas"),
("Brave", "QuaMas"),
("Calme", "QuaMas"),
("Courbe", "QuaMas"),

("Vive", "QuaFem"),
("Rude", "QuaFem"),
("Verte", "QuaFem"),
("Vieille", "QuaFem"),
("Basse", "QuaFem"),
("Belle", "QuaFem"),
("Blanche", "QuaFem"),
("Claire", "QuaFem"),
("Fière", "QuaFem"),
("Franche", "QuaFem"),
("Froide", "QuaFem"),
("Grande", "QuaFem"),
("Haute", "QuaFem"),
("Morne", "QuaFem"),
("Mort", "QuaFem"),
("Noble", "QuaFem"),
("Noire", "QuaFem"),
("Folle", "QuaFem"),
("Courte", "QuaFem"),
("Calme", "QuaFem"),
("Courbe", "QuaFem"),
("Droite", "QuaFem"),
("Dure", "QuaFem"),

("ecueil", "NomMas"),
("bourg", "NomMas"),
("castel", "NomMas"),
("champ", "NomMas"),
("château", "NomMas"),
("fond", "NomMas"),
("mont", "NomMas"),
("moulin", "NomMas"),
("pont", "NomMas"),
("port", "NomMas"),
("pré", "NomMas"),
("pic", "NomMas"),
("puy", "NomMas"),
("roc", "NomMas"),
("rocher", "NomMas"),
("tertre", "NomMas"),
("val", "NomMas"),
("valon", "NomMas"),
("lac", "NomMas"),
("bois", "NomMas"),
("bord", "NomMas"),
("cerf", "NomMas"),
("croc", "NomMas"),
("comble", "NomMas"),
("mur", "NomMas"),

("roche", "NomFem"),
("ville", "NomFem"),
("eau", "NomFem"),
("vigne", "NomFem"),
("terre", "NomFem"),
("forge", "NomFem"),
("maison", "NomFem"),
("mer", "NomFem"),
("rive", "NomFem"),
("roche", "NomFem"),
("ronce", "NomFem"),
("cime", "NomFem"),
("herbe", "NomFem"),
("citadelle", "NomFem"),
("passerelle", "NomFem"),
("butte", "NomFem"),
("colline", "NomFem"),
("brume", "NomFem"),
("cour", "NomFem"),
("douve", "NomFem"),
("dune", "NomFem"),
("fosse", "NomFem"),
("grange", "NomFem"),
("muraille", "NomFem"),
("plaine", "NomFem"),
("tour", "NomFem"),
("valée", "NomFem"),

("belette", "CreFemCon"),
("loutre", "CreFemCon"),
("marmotte", "CreFemCon"),
("mésange", "CreFemCon"),
("mouche", "CreFemCon"),
("mouette", "CreFemCon"),
("pieuvre", "CreFemCon"),
("wyverne", "CreFemCon"),
("grenouille", "CreFemCon"),
("marmotte", "CreFemCon"),

("anguille", "CreFemVoy"),
("hydre", "CreFemVoy"),
("araignée", "CreFemVoy"),
("abeille", "CreFemVoy"),

("rieuse", "AdjFemCre"),
("animmée", "AdjFemCre"),
("jaune", "AdjFemCre"),
("cuivrée", "AdjFemCre"),
("braisée", "AdjFemCre"),
("farcie", "AdjFemCre"),
("verte", "AdjFemCre"),
("malade", "AdjFemCre"),
("noire", "AdjFemCre"),
("fringante", "AdjFemCre"),
("malchanceuse", "AdjFemCre"),
("gourmande", "AdjFemCre"),
("fumée", "AdjFemCre"),
("crevée", "AdjFemCre"),
("enragée", "AdjFemCre"),
("rieuse", "AdjFemCre"),

("bougie", "ObjFemCon"),
("oreille", "ObjFemCon"),
("bouteille", "ObjFemCon"),
("chopine", "ObjFemCon"),
("couronne", "ObjFemCon"),
("cuillére", "ObjFemCon"),
("plume", "ObjFemCon"),
("poélle", "ObjFemCon"),
("table", "ObjFemCon"),
("chope", "ObjFemCon"),
("fleur", "ObjFemCon"),
("fléte", "ObjFemCon"),
("fourchette", "ObjFemCon"),
("barbe", "ObjFemCon"),
("lance", "ObjFemCon"),

("rouge", "AdjFemObj"),
("brélante", "AdjFemObj"),
("hurlante", "AdjFemObj"),
("percée", "AdjFemObj"),
("brisée", "AdjFemObj"),
("dorée", "AdjFemObj"),
("sale", "AdjFemObj"),
("noircie", "AdjFemObj"),
("fondue", "AdjFemObj"),

("chat", "CreMasCon"),
("chien", "CreMasCon"),
("griffon", "CreMasCon"),
("cochon", "CreMasCon"),
("dauphin", "CreMasCon"),
("dragon", "CreMasCon"),
("faucon", "CreMasCon"),
("gobelin", "CreMasCon"),
("héron", "CreMasCon"),
("mouton", "CreMasCon"),
("poisson", "CreMasCon"),
("poney", "CreMasCon"),
("renard", "CreMasCon"),
("sanglier", "CreMasCon"),
("troll", "CreMasCon"),
("blaireau", "CreMasCon"),
("chat", "CreMasCon"),
("forgeron", "CreMasCon"),
("poney", "CreMasCon"),
("poulet", "CreMasCon"),
("corbeau", "CreMasCon"),
("crapaud", "CreMasCon"),
("cochon", "CreMasCon"),
("cafard", "CreMasCon"),
("faucon", "CreMasCon"),
("hérisson", "CreMasCon"),
("héron", "CreMasCon"),
("sanglier", "CreMasCon"),
("troll", "CreMasCon"),
("dragon", "CreMasCon"),

("aigle", "CreMasVoy"),
("ours", "CreMasVoy"),

("blanc", "AdjMasCre"),
("jaune", "AdjMasCre"),
("fumé", "AdjMasCre"),
("rieur", "AdjMasCre"),
("sympathique", "AdjMasCre"),
("noir", "AdjMasCre"),
("enragé", "AdjMasCre"),
("malicieux", "AdjMasCre"),
("bleu", "AdjMasCre"),
("malchanceux", "AdjMasCre"),
("copieux", "AdjMasCre"),
("hurlant", "AdjMasCre"),
("sentimental", "AdjMasCre"),
("braisé", "AdjMasCre"),
("brulé", "AdjMasCre"),
("magique", "AdjMasCre"),
("fringant", "AdjMasCre"),
("insatiable", "AdjMasCre"),
("fraceur", "AdjMasCre"),
("chantant", "AdjMasCre"),

("luth", "ObjMasCon"),
("chaudron", "ObjMasCon"),
("comptoir", "ObjMasCon"),
("tonneau", "ObjMasCon"),
("bouclier", "ObjMasCon"),
("chaudron", "ObjMasCon"),
("chiffon", "ObjMasCon"),
("coin", "ObjMasCon"),
("glaive", "ObjMasCon"),

("rouge", "AdjMasObj"),
("brélant", "AdjMasObj"),
("hurlant", "AdjMasObj"),
("percé", "AdjMasObj"),
("brisé", "AdjMasObj"),
("doré", "AdjMasObj"),
("sale", "AdjMasObj"),
("noirci", "AdjMasObj"),
("fondu", "AdjMasObj"),
("vert", "AdjMasObj"),
("bleu", "AdjMasObj"),
("élimé", "AdjMasObj"),
("fondu", "AdjMasObj"),
("fendu", "AdjMasObj"),
("doré", "AdjMasObj"),

("cinq", "QuaNum"),
("deux", "QuaNum"),
("trois", "QuaNum"),
("quatre", "QuaNum"),
("cinq", "QuaNum"),
("six", "QuaNum"),
("cent", "QuaNum"),
("mille", "QuaNum"),

("Mahyar", "Perso"),
("Minst", "Perso"),
("Mirra", "Perso"),
("Avygael", "Perso"),
("Taklin", "Perso"),
("Rudolf", "Perso"),
("Argawen", "Perso"),
("Hadush", "Perso"),
("Ash", "Perso"),
("Pam", "Perso"),
("Rick Tapdur", "Perso"),
("Eris", "Perso"),
("Saumeth", "Perso"),
("Latur", "Perso"),
("Grecarsos", "Perso"),
("Trados", "Perso"),
("Burtath", "Perso"),
("Gigollel", "Perso"),
("Kolecan", "Perso"),
("Lodersan", "Perso"),
("Lacesor", "Perso"),
("Pamilion", "Perso"),
("Ascis", "Perso"),
("Etal", "Perso"),
("Druveth", "Perso"),
("Poncebrar", "Perso"),
("Bomis", "Perso"),
("Proris", "Perso"),
("Piscur", "Perso"),
("Kodien", "Perso"),
("Mecegrus", "Perso"),
("Jimican", "Perso"),
("Drae", "Perso"),
("Gige", "Perso"),
("Remithath", "Perso"),
("Pedus", "Perso"),
("Gisin", "Perso"),
("Siscel", "Perso"),
("Calin", "Perso"),
("Bertas", "Perso"),
("Baran", "Perso"),

("brasserie", "LieFemCon"),
("cabane", "LieFemCon"),
("hutte", "LieFemCon"),
("maison", "LieFemCon"),
("table", "LieFemCon"),
("taverne", "LieFemCon"),

("foyer", "LieMasCon"),
("géte", "LieMasCon"),
("bar", "LieMasCon"),
("bol", "LieMasCon"),
("chaudron", "LieMasCon"),
("chéne", "LieMasCon"),
("coin", "LieMasCon"),
("comptoire", "LieMasCon"),
("gobelet", "LieMasCon"),
("relais", "LieMasCon"),
("repaire", "LieMasCon"),
("tonneau", "LieMasCon"),
("mouchoir", "LieMasCon"),
("comptoir", "LieMasCon"),

("fume", "QuiNeu"),
("grogne", "QuiNeu"),
("grogne", "QuiNeu"),
("rote", "QuiNeu"),
("craque", "QuiNeu"),
("louche", "QuiNeu"),

("troll", "du"),
("rodeur", "du"),
("mage", "du"),
("sorcier", "du"),
("nain", "du"),
("voisin", "du"),
("voyageur", "du"),
("marcheur", "du"),
("coureur de jupons", "du"),
("grand-pére", "du"),
("vaillant", "du"),
("pélerin", "du"),
("pirate", "du"),

("or", "d"),
("argent", "d"),
("adamantium", "d"),

("quatres chemins", "des"),
("légendes", "des"),
("réves", "des"),
("plaisirs", "des"),
("quais", "des"),
("chansons", "des"),
("portes", "des"),
("caravanes", "des"),
("rencontres", "des"),
("pélerins", "des"),
("deux tours", "des"),
("petites personnes", "des"),
("halfelins", "des"),
("gobelins", "des"),

("longue barbe", "dela"),
("courtisane", "dela"),
("voisine", "dela"),
("petite personne", "dela"),

("Une fontaine", "lieu"),
("Un parc", "lieu"),
("Un lac", "lieu"),
("Une statue", "lieu"),
("Un édifice commémoratif", "lieu"),
("Un pont", "lieu"),
("Une tour abandonée", "lieu"),
("Un jardin", "lieu"),
("Un bosquet", "lieu"),
("Une place", "lieu"),
("Une maison biscornue", "lieu"),
("Une maison étrange", "lieu"),

("Agate rubanée", "gemmetype1"),
("Agate iris", "gemmetype1"),
("Agate de feu", "gemmetype1"),
("Agate-mousse", "gemmetype1"),
("Agate oeil de tigre", "gemmetype1"),
("Azurite", "gemmetype1"),
("Couronne d'argent", "gemmetype1"),
("Fluorite", "gemmetype1"),
("Hématite", "gemmetype1"),
("Ivoire", "gemmetype1"),
("Lapis-Lazuli", "gemmetype1"),
("Malachite", "gemmetype1"),
("Nelvine", "gemmetype1"),
("Néphrite", "gemmetype1"),
("Obsidienne", "gemmetype1"),
("Perle (irrégulère)", "gemmetype1"),
("Quartz bleu", "gemmetype1"),
("Quartz laiteux", "gemmetype1"),
("Rhodochronsite", "gemmetype1"),
("sanidine", "gemmetype1"),
("Turquoise", "gemmetype1"),
("Violine", "gemmetype1"),

("Andar", "gemmetype2"),
("Aventurine", "gemmetype2"),
("Calcédoine", "gemmetype2"),
("Chrysoprase", "gemmetype2"),
("Citrine", "gemmetype2"),
("Cornaline", "gemmetype2"),
("Héliotrope", "gemmetype2"),
("Hydrophane", "gemmetype2"),
("Iole", "gemmetype2"),
("Iolite", "gemmetype2"),
("Irtios", "gemmetype2"),
("Jaspe", "gemmetype2"),
("Onyx", "gemmetype2"),
("Orprase", "gemmetype2"),
("Péridot", "gemmetype2"),
("Phénalope", "gemmetype2"),
("Pierre de lune", "gemmetype2"),
("Quartz cristal de roche", "gemmetype2"),
("Quartz rose", "gemmetype2"),
("Quartz fumé", "gemmetype2"),
("Sardoine", "gemmetype2"),
("Sardonyx", "gemmetype2"),
("Spoduméne", "gemmetype2"),
("Tchazar", "gemmetype2"),
("Zircon", "gemmetype2"),

("Ambre", "gemmetype3"),
("Améthyste", "gemmetype3"),
("Chrysobéryl", "gemmetype3"),
("Coral", "gemmetype3"),
("Etoile d'eau", "gemmetype3"),
("Grenat rouge", "gemmetype3"),
("grenat vert sombre", "gemmetype3"),
("Jade", "gemmetype3"),
("jais", "gemmetype3"),
("Larmes de Laérale", "gemmetype3"),
("Peau d'agne", "gemmetype3"),
("Perle dorée", "gemmetype3"),
("Perle rose", "gemmetype3"),
("Perle argnetée", "gemmetype3"),
("Perle Blanche", "gemmetype3"),
("Spinelle rouge", "gemmetype3"),
("Spinelle rouge sombre", "gemmetype3"),
("Spinelle vert sombre", "gemmetype3"),
("Tourmaline blanche", "gemmetype3"),
("Tourmaline dorée", "gemmetype3"),
("Tourmaline rose", "gemmetype3"),
("Perle d'argent", "gemmetype3"),

("Aigue-marine", "gemmetype4"),
("Alexandrite", "gemmetype4"),
("Grenat violet", "gemmetype4"),
("Perle noire", "gemmetype4"),
("Spinelle bleu nuit", "gemmetype4"),
("Topaze jaune d'or", "gemmetype4"),

("Corbinard", "gemmetype5"),
("Coridon jaune ambré", "gemmetype5"),
("Coridon pourpre", "gemmetype5"),
("Coridon noir", "gemmetype5"),
("Coridon bleu", "gemmetype5"),
("Emeraude", "gemmetype5"),
("Jade de sépulere", "gemmetype5"),
("Larmes rouges", "gemmetype5"),
("Opale blanche", "gemmetype5"),
("opale noire de feu", "gemmetype5"),
("Opale d'eau", "gemmetype5"),
("Orle", "gemmetype5"),
("Rubis étoilé", "gemmetype5"),
("Saphir étoilé noir", "gemmetype5"),
("Saphir étoilé bleu", "gemmetype5"),

("Belgurile", "gemmetype6"),
("Diamant limpide", "gemmetype6"),
("Diamant jaune", "gemmetype6"),
("Diamant rose", "gemmetype6"),
("Diamant brun", "gemmetype6"),
("Diamant bleu", "gemmetype6"),
("Emeraude du vert le plus clair", "gemmetype6"),
("Hyacinthe", "gemmetype6"),
("Larmes de roi", "gemmetype6"),
("Rubis", "gemmetype6"),

("Barbare", "typedeherosmas"),
("Barde", "typedeherosmas"),
("Druide", "typedeherosmas"),
("Ensorceleur", "typedeherosmas"),
("Guerrier", "typedeherosmas"),
("Magicien", "typedeherosmas"),
("Moine", "typedeherosmas"),
("Paladin", "typedeherosmas"),
("Prêtre", "typedeherosmas"),
("Rôdeur", "typedeherosmas"),
("Roublard", "typedeherosmas"),

("Barbare", "typedeherosfem"),
("Barde", "typedeherosfem"),
("Druidesse", "typedeherosfem"),
("Ensorceleuse", "typedeherosfem"),
("Guerrière", "typedeherosfem"),
("Magicienne", "typedeherosfem"),
("Moine", "typedeherosfem"),
("Paladine", "typedeherosfem"),
("Prêtresse", "typedeherosfem"),
("Rôdeuse", "typedeherosfem"),
("Roublarde", "typedeherosfem"),

("Un acrobate", "hommedupeuple"),
("Un jongleur", "hommedupeuple"),
("Un artiste de rue", "hommedupeuple"),
("Un(e) prostitué(e)", "hommedupeuple"),
("Un tanneur", "hommedupeuple"),
("Un potier", "hommedupeuple"),
("Un menuisier", "hommedupeuple"),
("Un barbier", "hommedupeuple"),
("Un horloger", "hommedupeuple"),
("Un crieur public", "hommedupeuple"),

("Un soigneur", "adepte"),
("Un alchimiste", "adepte"),
("Un herboriste", "adepte"),
("Un apothicaire", "adepte"),
("Un scribe", "adepte"),

("Un tisserand", "expert"),
("Un palefrenier", "expert"),
("Un architecte", "expert"),
("Un forgeron", "expert"),
("Un armurier", "expert"),
("Un artisan du cuir", "expert"),
("Un chasseur", "expert"),
("Un tailleur de pierre", "expert"),
("Un joaillier", "expert"),
("Un cordonnier", "expert"),
("Un charpentier", "expert"),
("Un maçon", "expert"),
("Un meûnier", "expert"),
("Un couturier", "expert"),
("Un boquetier", "expert"),
("Un bourreau", "expert"),
("Un calamier ", "expert"),
("Un homme de loi", "expert"),
("Un assassin", "expert"),
("Un navigateur", "expert"),
("Un guide", "expert"),
("Un fromager", "expert"),
("Un épicier", "expert"),
("Un vendeur d'objet rare", "expert"),
("Un boulanger", "expert"),

("Un dispensaire", "commerce"),
("Une étable", "commerce"),
("Une salle de jeux", "commerce"),
("Une petite échoppe de magie", "commerce"),
("Une librairie (non magique)", "commerce"),
("Un moulin", "commerce"),
("Un maréchal-ferrant", "commerce"),
("Une maison de joie", "commerce"),
("Une menuiserie", "commerce"),
("Un hôtel", "commerce"),
("Une épicerie", "commerce"),
("Une boulangerie", "commerce"),
("Un temple d'une divinité bonne", "commerce"),
("Une temple d'une divinité mauvaise", "commerce"),

("Un chantier maritime", "expertmarin"),
("Une capitainerie", "expertmarin"),
("Un chantier naval", "expertmarin"),
("Un port", "expertmarin"),
("Une poissonnerie", "expertmarin"),

("Un cartographe", "commercemarin"),
("Une équipe de mousses", "commercemarin"),
("Un capitaine", "commercemarin"),
("Un batelier", "commercemarin"),
("Un poissonnier", "commercemarin"),

("Impératrice", "titrenoblessefemfull"),
("Reine", "titrenoblessefemfull"),
("Grande-duchesse", "titrenoblessefemfull"),
("Archiduchesse", "titrenoblessefemfull"),
("Duchesse", "titrenoblessefemfull"),
("Princesse", "titrenoblessefemfull"),
("Marquise", "titrenoblessefemfull"),
("Comtesse", "titrenoblessefemfull"),
("Vicomtesse", "titrenoblessefemfull"),
("Baronne", "titrenoblessefemfull"),
("Dame", "titrenoblessefemfull"),
("Première Impératrice", "titrenoblessefemfull"),
("Première Reine", "titrenoblessefemfull"),
("Première Grande-duchesse", "titrenoblessefemfull"),
("Première Archiduchesse", "titrenoblessefemfull"),
("Première Duchesse", "titrenoblessefemfull"),
("Première Princesse", "titrenoblessefemfull"),
("Première Marquise", "titrenoblessefemfull"),
("Première Comtesse", "titrenoblessefemfull"),
("Première Vicomtesse", "titrenoblessefemfull"),
("Première Baronne", "titrenoblessefemfull"),
("Première Dame", "titrenoblessefemfull"),
("Seconde Impératrice", "titrenoblessefemfull"),
("Seconde Reine", "titrenoblessefemfull"),
("Seconde Grande-duchesse", "titrenoblessefemfull"),
("Seconde Archiduchesse", "titrenoblessefemfull"),
("Seconde Duchesse", "titrenoblessefemfull"),
("Seconde Princesse", "titrenoblessefemfull"),
("Seconde Marquise", "titrenoblessefemfull"),
("Seconde Comtesse", "titrenoblessefemfull"),
("Seconde Vicomtesse", "titrenoblessefemfull"),
("Seconde Baronne", "titrenoblessefemfull"),
("Seconde Dame", "titrenoblessefemfull"),

("Empereur", "titrenoblessemasfull"),
("Roi", "titrenoblessemasfull"),
("Grand-duc", "titrenoblessemasfull"),
("Archiduc", "titrenoblessemasfull"),
("Duc", "titrenoblessemasfull"),
("Prince", "titrenoblessemasfull"),
("Marquis", "titrenoblessemasfull"),
("Comte", "titrenoblessemasfull"),
("Vicomte", "titrenoblessemasfull"),
("Baron", "titrenoblessemasfull"),
("Chevalier", "titrenoblessemasfull"),
("Écuyer", "titrenoblessemasfull"),
("Seigneur", "titrenoblessemasfull"),
("Dauphin", "titrenoblessemasfull"),
("Monsieur", "titrenoblessemasfull"),
("Banneret", "titrenoblessemasfull"),
("Baronnet", "titrenoblessemasfull"),
("Châtelain", "titrenoblessemasfull"),
("Prince de sang", "titrenoblessemasfull"),
("Premier Empereur", "titrenoblessemasfull"),
("Premier Roi", "titrenoblessemasfull"),
("Premier Grand-duc", "titrenoblessemasfull"),
("Premier Archiduc ", "titrenoblessemasfull"),
("Premier Duc ", "titrenoblessemasfull"),
("Premier Prince", "titrenoblessemasfull"),
("Premier Marquis", "titrenoblessemasfull"),
("Premier Comte", "titrenoblessemasfull"),
("Premier Vicomte", "titrenoblessemasfull"),
("Premier Baron", "titrenoblessemasfull"),
("Premier Chevalier", "titrenoblessemasfull"),
("Premier écuyer", "titrenoblessemasfull"),
("Premier Seigneur", "titrenoblessemasfull"),
("Premier Dauphin", "titrenoblessemasfull"),
("Premier Banneret", "titrenoblessemasfull"),
("Premier Baronnet", "titrenoblessemasfull"),
("Premier Prince de sang", "titrenoblessemasfull"),
("Premier Châtelain", "titrenoblessemasfull"),
("Second Empereur", "titrenoblessemasfull"),
("Second Roi", "titrenoblessemasfull"),
("Second Grand-duc", "titrenoblessemasfull"),
("Second Archiduc", "titrenoblessemasfull"),
("Second Duc", "titrenoblessemasfull"),
("Second Prince", "titrenoblessemasfull"),
("Second Marquis", "titrenoblessemasfull"),
("Second Comte", "titrenoblessemasfull"),
("Second Vicomte", "titrenoblessemasfull"),
("Second Baron", "titrenoblessemasfull"),
("Second Chevalier", "titrenoblessemasfull"),
("Second écuyer", "titrenoblessemasfull"),
("Second Seigneur", "titrenoblessemasfull"),
("Second Dauphin", "titrenoblessemasfull"),
("Second Banneret", "titrenoblessemasfull"),
("Second Baronnet", "titrenoblessemasfull"),
("Second Prince de sang", "titrenoblessemasfull"),

("Duchesse", "titrenoblessefemfaible"),
("Marquise", "titrenoblessefemfaible"),
("Comtesse", "titrenoblessefemfaible"),
("Vicomtesse", "titrenoblessefemfaible"),
("Baronne", "titrenoblessefemfaible"),
("Dame", "titrenoblessefemfaible"),
("Première Duchesse", "titrenoblessefemfaible"),
("Première Marquise", "titrenoblessefemfaible"),
("Première Comtesse", "titrenoblessefemfaible"),
("Première Vicomtesse", "titrenoblessefemfaible"),
("Première Baronne", "titrenoblessefemfaible"),
("Première Dame", "titrenoblessefemfaible"),
("Seconde Duchesse", "titrenoblessefemfaible"),
("Seconde Marquise", "titrenoblessefemfaible"),
("Seconde Comtesse", "titrenoblessefemfaible"),
("Seconde Vicomtesse", "titrenoblessefemfaible"),
("Seconde Baronne", "titrenoblessefemfaible"),
("Seconde Dame", "titrenoblessefemfaible"),

("Marquis", "titrenoblessemasfaible"),
("Comte", "titrenoblessemasfaible"),
("Vicomte", "titrenoblessemasfaible"),
("Baron", "titrenoblessemasfaible"),
("Chevalier", "titrenoblessemasfaible"),
("Écuyer", "titrenoblessemasfaible"),
("Seigneur", "titrenoblessemasfaible"),
("Dauphin", "titrenoblessemasfaible"),
("Monsieur", "titrenoblessemasfaible"),
("Banneret", "titrenoblessemasfaible"),
("Baronnet", "titrenoblessemasfaible"),
("Châtelain", "titrenoblessemasfaible"),
("Premier Marquis", "titrenoblessemasfaible"),
("Premier Comte", "titrenoblessemasfaible"),
("Premier Vicomte", "titrenoblessemasfaible"),
("Premier Baron", "titrenoblessemasfaible"),
("Premier Chevalier", "titrenoblessemasfaible"),
("Premier Écuyer", "titrenoblessemasfaible"),
("Premier Seigneur", "titrenoblessemasfaible"),
("Premier Dauphin", "titrenoblessemasfaible"),
("Premier Banneret", "titrenoblessemasfaible"),
("Premier Baronnet", "titrenoblessemasfaible"),
("Premier Châtelain", "titrenoblessemasfaible"),
("Second Marquis", "titrenoblessemasfaible"),
("Second Comte", "titrenoblessemasfaible"),
("Second Vicomte", "titrenoblessemasfaible"),
("Second Baron", "titrenoblessemasfaible"),
("Second Chevalier", "titrenoblessemasfaible"),
("Second Écuyer", "titrenoblessemasfaible"),
("Second Seigneur", "titrenoblessemasfaible"),
("Second Dauphin", "titrenoblessemasfaible"),
("Second Banneret", "titrenoblessemasfaible"),
("Second Baronnet", "titrenoblessemasfaible"),

("un maire", "typedirigeanttradisolo"),
("un noble", "typedirigeanttradisolo"),
("un aventurier à la retraite", "typedirigeanttradisolo"),
("un riche marchand", "typedirigeanttradisolo"),
("un prêtre de faible puissance", "typedirigeanttradisolo"),
("un mage de faible puissance", "typedirigeanttradisolo"),
("un troubadour", "typedirigeanttradisolo"),
("un membre des ménestrels", "typedirigeanttradisolo"),
("un officier", "typedirigeanttradisolo"),
("un commandant", "typedirigeanttradisolo"),
("un sénéchal", "typedirigeanttradisolo"),
("un baron", "typedirigeanttradisolo"),
("un compte", "typedirigeanttradisolo"),
("un grand-duc", "typedirigeanttradisolo"),
("un marquis", "typedirigeanttradisolo"),
("un duc", "typedirigeanttradisolo"),

("un conseil municipal", "typedirigeanttradimulti"),
("un ensemble de marchands", "typedirigeanttradimulti"),
("un ensemble de prêtres de différents cultes de la nature", "typedirigeanttradimulti"),
("un groupe d'aventuriers à la retraite", "typedirigeanttradimulti"),
("un ensemble de prêtres de confession bienveillante", "typedirigeanttradimulti"),

("une guilde de voleurs", "typedirigeantinhabsolo"),
("une guilde de marchands", "typedirigeantinhabsolo"),
("une guilde d'artisans", "typedirigeantinhabsolo"),
("une guilde d'assassins", "typedirigeantinhabsolo"),
("une guilde de mercenaires", "typedirigeantinhabsolo"),

("une guilde de voleurs", "typedirigeantinhabmulti"),
("une guilde de marchands", "typedirigeantinhabmulti"),
("une guilde d'artisans", "typedirigeantinhabmulti"),
("une guilde d'assassins", "typedirigeantinhabmulti"),
("une guilde de mercenaires", "typedirigeantinhabmulti"),

("un mage isolé puissant", "typedirigeantinmagsolo"),
("un mage isolé très puissant et versatile", "typedirigeantinmagsolo"),
("un ensorceleur versatile", "typedirigeantinmagsolo"),
("un chaman au charisme extraordinaire", "typedirigeantinmagsolo"),
("un prête ayant une foi inébranlable", "typedirigeantinmagsolo"),

("un conseil de mages", "typedirigeantinmagmulti"),
("un temple de confession bonne", "typedirigeantinmagmulti"),
("un ordre religieux extrémiste", "typedirigeantinmagmulti"),
("un ordre religieux totalitaire", "typedirigeantinmagmulti"),

("un magicien ayant pactisé avec un démon afin de ne plus veillir", "monstrueux"),
("un doppelgänger usurpant l'identité du vrai dirigeant", "monstrueux"),
("un pion au services d'une organisation", "monstrueux"),
("un pion devant rendre des comptes à une créature puissantes (dragon, démon,...)", "monstrueux"),
("dirigé par un flageleur mental qui s'amuse", "monstrueux"),

("d'un abri fortifié", "ChateauTaille1"),
("d'un refuge fortifié", "ChateauTaille1"),
("d'une habitation fortifiée", "ChateauTaille1"),
("d'une maison fortifiée", "ChateauTaille1"),
("d'une demeure fortifiée", "ChateauTaille1"),
("d'une résidence fortifiée", "ChateauTaille1"),
("d'un manoir fortifié", "ChateauTaille1"),

("d'un abri fortifié", "ChateauTaille2"),
("d'un refuge fortifié", "ChateauTaille2"),
("d'une habitation fortifiée", "ChateauTaille2"),
("d'une maison fortifiée", "ChateauTaille2"),
("d'une demeure fortifiée", "ChateauTaille2"),
("d'une résidence fortifiée", "ChateauTaille2"),
("d'un manoir fortifié", "ChateauTaille2"),
("d'un palais fortifié", "ChateauTaille2"),
("d'un donjon", "ChateauTaille2"),

("d'un abri fortifié", "ChateauTaille3"),
("d'un refuge fortifié", "ChateauTaille3"),
("d'une habitation fortifiée", "ChateauTaille3"),
("d'une maison fortifiée", "ChateauTaille3"),
("d'une demeure fortifiée", "ChateauTaille3"),
("d'une résidence fortifiée", "ChateauTaille3"),
("d'un manoir fortifié", "ChateauTaille3"),
("d'un palais fortifié", "ChateauTaille3"),
("d'un donjon", "ChateauTaille3"),
("d'une tour", "ChateauTaille3"),
("d'une bastille", "ChateauTaille3"),
("d'une place-forte", "ChateauTaille3"),

("d'une habitation fortifiée", "ChateauTaille4"),
("d'une maison fortifiée", "ChateauTaille4"),
("d'une emeure fortifiée", "ChateauTaille4"),
("d'une résidence fortifiée", "ChateauTaille4"),
("d'un manoir fortifié", "ChateauTaille4"),
("d'un palais fortifié", "ChateauTaille4"),
("d'un donjon", "ChateauTaille4"),
("d'un châtelet", "ChateauTaille4"),
("d'une tour", "ChateauTaille4"),
("d'une bastille", "ChateauTaille4"),
("d'un manoir fortifié", "ChateauTaille4"),
("d'un palais fortifié", "ChateauTaille4"),
("d'un châtelet", "ChateauTaille4"),
("d'un donjon", "ChateauTaille4"),
("d'une tour", "ChateauTaille4"),
("d'une bastille", "ChateauTaille4"),
("d'une place-forte", "ChateauTaille4"),
("d'un fortin", "ChateauTaille4"),
("d'un fort", "ChateauTaille4"),

("d'un donjon", "ChateauTaille6"),
("d'une tour", "ChateauTaille6"),
("d'une bastille", "ChateauTaille6"),
("d'une place-forte", "ChateauTaille6"),
("d'un châtelet", "ChateauTaille6"),
("d'un fortin", "ChateauTaille6"),
("d'un fort", "ChateauTaille6"),
("d'une forteresse", "ChateauTaille6"),

("d'une tour", "ChateauTaille7"),
("d'une bastille", "ChateauTaille7"),
("d'une place-forte", "ChateauTaille7"),
("d'un fortin", "ChateauTaille7"),
("d'un châtelet", "ChateauTaille7"),
("d'un fort", "ChateauTaille7"),
("d'une forteresse", "ChateauTaille7"),
("d'un château", "ChateauTaille7"),
("d'une citadelle", "ChateauTaille7"),

("d'une bastille", "ChateauTaille8"),
("d'une place-forte", "ChateauTaille8"),
("d'un fortin", "ChateauTaille8"),
("d'un fort", "ChateauTaille8"),
("d'une forteresse", "ChateauTaille8"),
("d'un château", "ChateauTaille8"),
("d'une citadelle", "ChateauTaille8"),

("Un maître d'armes", "ChateauAddon"),
("Un tanneur dont les armures de cuir sont réputées", "ChateauAddon"),
("Un maître d'armes à la retraite", "ChateauAddon"),
("Un bretteur hors pair", "ChateauAddon"),
("Une guilde de guerriers", "ChateauAddon"),
("Un centre d'entraînement militaire", "ChateauAddon"),
("Un armurier de renom", "ChateauAddon"),
("Une forge fabricant des armes proches de la perfection", "ChateauAddon"),
("Une ancien chef militaire ayant gagné de grandes guerres", "ChateauAddon"),
("Un combattant utilisant des armes particulières que peu connaissent", "ChateauAddon"),
("Une academie militaire formant de bons combattants", "ChateauAddon"),
("Une fabrique de balistes", "ChateauAddon"),
("Une forge de renom", "ChateauAddon"),
("Un tournois d'épéistes connu de part le monde", "ChateauAddon"),
("Un tournois d'épéistes connu dans toute la région", "ChateauAddon"),
("Un tournois d'archerie connu de part le monde", "ChateauAddon"),
("Un tournois d'archerie connu dans toute la région", "ChateauAddon"),
("Un tournois de cavalerie connu de part le monde", "ChateauAddon"),
("Un tournois de cavalerie connu dans toute la région", "ChateauAddon"),
("Un festival de joutes diverses où chacun peut prouver sa bravoure", "ChateauAddon"),
("Une joute équestre", "ChateauAddon"),
("Un facteur d'arcs reconnu pour ses créations", "ChateauAddon"),
("Un forgeron reconnu pour ses créations", "ChateauAddon"),

("<span style='border-bottom: 1px black dotted;' title='Ouverture longue et étroite dans un mur pour tirer à l\'arc ou à l\'arbalète'>Archère</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Ouverture défendant généralement une porte permettant de jeter des projectiles verticalement.'>Assommoir</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Ouvrage fortifié avancé, servant à défendre la porte d\'une ville ou d\'un château.'>Barbacane</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Cour extérieure protégée par les murailles d\'un château.'>Basse-Cour</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Ouvrage avancé à deux flancs et deux faces faisant saillie, placé généralement sur l\'enceinte d\'un château. Apparu au milieu du XVI ème siècle en Italie.'>Bastion</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Parement de pierre formant une bosse plus ou moins saillante par rapport à ses arêtes.'>Bossage</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Logette à mâchicoulis faisant saillie, utilisée comme ouvrage de défense qui surplombe, dans la plupart des cas, une ouverture.'>Bretèche</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Emplacement situé dans le flanc d\'une place-forte pour défendre le fossé. La casemate n'est généralement pas reliée au reste du château.'>Casemate</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Chemin au sommet des murs, souvent protégé par un parapet.'>Chemin de ronde</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Muraille enveloppant une tour ou quelque édifice fortifié.'>Chemise</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Elément encastré en saillie sur un mur pour supporter un encorbellement. Les corbeaux étaient soit en bois, soit en pierre (appelés alors consoles)'>Corbeau</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Elément de muraille reliant deux bastions ou deux tours flanquantes.'>Courtine</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Ouverture pratiquée dans le parapet défensif.'>Créneau</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Tour maîtresse d\'un château fort médiéval, parfois demeure du seigneur du château.'>Donjon</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Fossé parfois rempli d\'eau entourant le château.'>Douves</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Guérite placée en surplomb sur une muraille fortifiée ou une tour.'>Echauguette</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Tourelle surmontant l\'escalier d\'accès au sommet d\'une tour.'>Guette</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Grille de fer ou de bois coulissant de haut en bas.'>Herse</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Galerie de bois établie en surplomb autour du sommet des murs d\'un château.'>Hourd</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Palissade de bois entourant les châteaux ou les sites fortifiés.'>Lice</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Construction en surplomb des remparts permettant de jeter des projectiles verticalement.'>Mâchicoulis</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Partie pleine d\'un rempart entre deux créneaux.'>Merlon</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Ouverture étroite pratiquée dans le mur d\'un ouvrage fortifié pour permettre l\'observation et l\'envoi de projectiles.'>Meurtrière</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Sortes de petites casemates extérieures situées dans le fossé et accolées à l\'escarpe'>Moineau</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Fosses, ou cachots souterrains dans lesquels les prisonniers sont \'oubliés\' jusqu\'à leur mort.'>Oubliettes</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Face visible du mur fait de pierres de taille'>Parement</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Guérite en maçonnerie ainsi nommée à cause de sa forme ronde au toit conique.'>Poivrière</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Pont mobile au dessus d\'un fossé, dont le tablier se relève pour fermer l\'accès au château.'>Pont-levis</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Petite porte dérobée qui servait à fuir ou à faire entrer des renforts à l\'insu des assiégeants.'>Poterne</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Petit ouvrage de fortification isolé et fermé.'>Redoute</span>", "ChateauAmelioration"),
("<span style='border-bottom: 1px black dotted;' title='Tour permettant d\'effectuer des tirs parallèles au mur à défendre.'>Tour flanquante</span>", "ChateauAmelioration"),

("sont souvent laissées sans protection.", "detailportefaible"),
("ne tiennent plus que part un gond", "detailportefaible"),
("tomberaient si un enfant venait à s'appuyer dessus", "detailportefaible"),
("ne tiennent que par habitude", "detailportefaible"),
("ne sont jamais gardées", "detailportefaible"),
("laissent passer le vent tout autant que les malfrats", "detailportefaible"),
("devaient être belles", "detailportefaible"),

("ne sont jamais laissées sans protection.", "detailportemoyen"),
("ne sont jamais laissée sans protection et la milice tourne jour et nuit.", "detailportemoyen"),
("sont fait de bois solide et de renfort métalique.", "detailportemoyen"),
("sont renforcées et offrent une bonne protection", "detailportemoyen"),

("peuvent être fermées rapidement avec une herse et une porte de bois massive renforcée de métal", "detailportehaut"),
("sont en bois solide et possédent des meurtrieres", "detailportehaut"),
("se ferme magiquement sous un simple mot de commande", "detailportehaut"),
("on déjà résisté à bon nombre d'essai d'intrusion et encore personne ne les a franchit de force.", "detailportehaut"),

("de la pierre", "listeexportfaible"),
("du porc", "listeexportfaible"),
("des chevaux", "listeexportfaible"),
("des esclaves", "listeexportfaible"),
("du boeuf", "listeexportfaible"),
("du charbon", "listeexportfaible"),
("des herbes", "listeexportfaible"),
("du bétail", "listeexportfaible"),
("des armes", "listeexportfaible"),
("des produits en cuir", "listeexportfaible"),
("des olives", "listeexportfaible"),
("du sel", "listeexportfaible"),
("du tissus", "listeexportfaible"),
("des minerais de fer", "listeexportfaible"),
("de la laine", "listeexportfaible"),
("de la bière", "listeexportfaible"),
("du fromage", "listeexportfaible"),
("des fourrures", "listeexportfaible"),
("du thé", "listeexportfaible"),
("des fruits", "listeexportfaible"),
("des betterave sucriaires", "listeexportfaible"),
("des graines", "listeexportfaible"),
("du bois", "listeexportfaible"),

("des herbes-à-pipe", "listeexportmoyen"),
("des herbes rares", "listeexportmoyen"),
("de la soie", "listeexportmoyen"),
("du vin", "listeexportmoyen"),
("du café", "listeexportmoyen"),
("du porc", "listeexportmoyen"),
("des chevaux", "listeexportmoyen"),
("des esclaves", "listeexportmoyen"),
("du boeuf", "listeexportmoyen"),
("du charbon", "listeexportmoyen"),
("des herbes", "listeexportmoyen"),
("des herbes médicinales", "listeexportmoyen"),
("du bétail", "listeexportmoyen"),
("des armes", "listeexportmoyen"),
("des armes de qualité supérieure", "listeexportmoyen"),
("des vêtements", "listeexportmoyen"),
("des produits en cuir", "listeexportmoyen"),
("des légumes", "listeexportmoyen"),
("des tissus", "listeexportmoyen"),
("du fer", "listeexportmoyen"),
("de l'huile d'olive", "listeexportmoyen"),
("des tapis", "listeexportmoyen"),
("de la bière", "listeexportmoyen"),
("du fromage", "listeexportmoyen"),
("des minerais d'argent", "listeexportmoyen"),
("des fourrures", "listeexportmoyen"),
("de l'ivoire", "listeexportmoyen"),
("du thé", "listeexportmoyen"),
("des fruits", "listeexportmoyen"),
("du sucre", "listeexportmoyen"),
("des fournitures de caravanes", "listeexportmoyen"),
("du cuivre", "listeexportmoyen"),
("des graines", "listeexportmoyen"),
("des poteries", "listeexportmoyen"),
("du bois", "listeexportmoyen"),

("de l'encens", "listeexportfort"),
("de  la soie", "listeexportfort"),
("du vin", "listeexportfort"),
("des livres", "listeexportfort"),
("du café", "listeexportfort"),
("du porc", "listeexportfort"),
("des chevaux", "listeexportfort"),
("des chevaux pur-sang", "listeexportfort"),
("des objets magiques", "listeexportfort"),
("du parfum", "listeexportfort"),
("des esclaves", "listeexportfort"),
("du boeuf", "listeexportfort"),
("des herbes", "listeexportfort"),
("des herbes médicinales", "listeexportfort"),
("du bétail", "listeexportfort"),
("des perles", "listeexportfort"),
("des armes", "listeexportfort"),
("des armes de qualité supérieure", "listeexportfort"),
("des objets d'art", "listeexportfort"),
("des vêtements", "listeexportfort"),
("des vêtements d'apparat", "listeexportfort"),
("de l'or", "listeexportfort"),
("du verre", "listeexportfort"),
("des produits en cuir", "listeexportfort"),
("des produits en cuir d'excellente qualité", "listeexportfort"),
("des légumes", "listeexportfort"),
("du tissu", "listeexportfort"),
("du fer", "listeexportfort"),
("des gemmes", "listeexportfort"),
("des bijoux", "listeexportfort"),
("de l'huile d'olive", "listeexportfort"),
("des épices", "listeexportfort"),
("des tapis", "listeexportfort"),
("de la bière", "listeexportfort"),
("du fromage", "listeexportfort"),
("de l'argent", "listeexportfort"),
("des fourrures", "listeexportfort"),
("de l'ivoire", "listeexportfort"),
("du thé", "listeexportfort"),
("des fruits", "listeexportfort"),
("des fournitures de caravanes", "listeexportfort"),
("du cuivre", "listeexportfort"),
("des graines", "listeexportfort"),
("des poteries", "listeexportfort"),
("du bois précieux", "listeexportfort"),

("de l'huile de baleine", "listeexportmaritimefull"),
("des fruits de mer", "listeexportmaritimefull"),
("des perles", "listeexportmaritimefull"),
("des fournitures de navires", "listeexportmaritimefull"),
("du sel", "listeexportmaritimefull"),
("des cordages", "listeexportmaritimefull"),
("des navires", "listeexportmaritimefull"),

("des fournitures de navires", "listeexportmaritimefaible"),
("du sel", "listeexportmaritimefaible"),
("des cordages", "listeexportmaritimefaible"),
("des navires (barque et chaloupe)", "listeexportmaritimefaible"),

("de la maison Araviir", "nomfamdrow"),
("de la maison GoDel'ndar", "nomfamdrow"),
("de la maison Fey-neld", "nomfamdrow"),
("de la maison Non'duis", "nomfamdrow"),
("de la maison Mysek", "nomfamdrow"),
("de la maison Aravir", "nomfamdrow"),
("de la maison Baeund", "nomfamdrow"),
("de la maison De'th", "nomfamdrow"),
("de la maison Hlalyl", "nomfamdrow"),
("de la maison Maeduis", "nomfamdrow"),
("de la maison Zaulynt'te", "nomfamdrow"),
("de la maison Alere", "nomfamdrow"),
("de la maison Kermnche", "nomfamdrow"),
("de la maison Eiduis", "nomfamdrow"),
("de la maison OuDen", "nomfamdrow"),
("de la maison Hupatt", "nomfamdrow"),
("de la maison Tekelarn", "nomfamdrow"),
("de la maison Kervs", "nomfamdrow"),
("de la maison Rival", "nomfamdrow"),
("de la maison DeDeep", "nomfamdrow"),
("de la maison Zaunche", "nomfamdrow"),
("de la maison Meirysek", "nomfamdrow"),
("de la maison AuDeep", "nomfamdrow"),
("de la maison Freni", "nomfamdrow"),
("de la maison Rith", "nomfamdrow"),
("de la maison Ribrandar", "nomfamdrow"),
("de la maison Myund", "nomfamdrow"),
("de la maison Ken", "nomfamdrow"),
("de la maison Tekeren", "nomfamdrow"),
("de la maison Zauund", "nomfamdrow"),
("de la maison Eianrafin", "nomfamdrow"),
("de la maison Araquar", "nomfamdrow"),
("de la maison Arkheund", "nomfamdrow"),
("de la maison HuvryDen", "nomfamdrow"),
("de la maison Huneld", "nomfamdrow"),
("de la maison Clafin", "nomfamdrow"),
("de la maison Everitt", "nomfamdrow"),
("de la maison Desni", "nomfamdrow"),
("de la maison Kesek", "nomfamdrow"),
("de la maison Arator", "nomfamdrow"),
("de la maison Baneld", "nomfamdrow"),
("de la maison Tekeval", "nomfamdrow"),
("de la maison Eilyl", "nomfamdrow"),
("de la maison Evermar", "nomfamdrow"),
("de la maison Hlairyn", "nomfamdrow"),
("de la maison Bate", "nomfamdrow"),
("de la maison Helvini", "nomfamdrow"),
("de la maison Desleslyl", "nomfamdrow"),
("de la maison Noduis", "nomfamdrow"),
("de la maison Noni", "nomfamdrow"),
("de la maison Gourund", "nomfamdrow"),
("de la maison Kebran", "nomfamdrow"),
("de la maison Keni", "nomfamdrow"),
("de la maison Arkhevryta", "nomfamdrow"),
("de la maison Toth", "nomfamdrow"),
("de la maison Zeiryval", "nomfamdrow"),
("de la maison Aleddator", "nomfamdrow"),
("de la maison Keund", "nomfamdrow"),
("de la maison Nosek", "nomfamdrow"),
("de la maison Kirvs", "nomfamdrow"),
("de la maison Fey-ta", "nomfamdrow"),
("de la maison Hlaren", "nomfamdrow"),
("de la maison Tolyl", "nomfamdrow"),
("de la maison Zaulynt'und", "nomfamdrow"),
("de la maison Clarvs", "nomfamdrow"),
("de la maison Zevir", "nomfamdrow"),
("de la maison Tore", "nomfamdrow"),
("de la maison Nofin", "nomfamdrow"),
("de la maison Freduis", "nomfamdrow"),
("de la maison Frefin", "nomfamdrow"),
("de la maison Helviirynche", "nomfamdrow"),
("de la maison Do'n", "nomfamdrow"),
("de la maison Evehel", "nomfamdrow"),
("de la maison Huni", "nomfamdrow"),
("de la maison Zen'sek", "nomfamdrow"),
("de la maison Eivir", "nomfamdrow"),
("de la maison Zeren", "nomfamdrow"),
("de la maison Kilarn", "nomfamdrow"),
("de la maison Huurtor", "nomfamdrow"),
("de la maison Maendar", "nomfamdrow"),
("de la maison ToDeep", "nomfamdrow"),
("de la maison Auni", "nomfamdrow"),
("de la maison Everen", "nomfamdrow"),
("de la maison Eith", "nomfamdrow"),
("de la maison Noneld", "nomfamdrow"),
("de la maison Mebrakan", "nomfamdrow"),
("de la maison Kiirytyl", "nomfamdrow"),
("de la maison Deshel", "nomfamdrow"),
("de la maison Basste", "nomfamdrow"),
("de la maison Goriviir", "nomfamdrow"),
("de la maison Gondar", "nomfamdrow"),
("de la maison Eveviir", "nomfamdrow"),
("de la maison Hulyl", "nomfamdrow"),
("de la maison Myndar", "nomfamdrow"),
("de la maison de lynt'vir", "nomfamdrow"),
("de la maison Goval", "nomfamdrow"),
("de la maison Zena", "nomfamdrow"),
("de la maison Do'n'eren", "nomfamdrow"),
("de la maison RiDen", "nomfamdrow"),
("de la maison Claund", "nomfamdrow"),
("de la maison Clavir", "nomfamdrow"),
("de la maison Fey-Deep", "nomfamdrow"),
("de la maison Kinche", "nomfamdrow"),
("de la maison Helvitt", "nomfamdrow"),
("de la maison Fey-ntt", "nomfamdrow"),
("de la maison Gota", "nomfamdrow"),
("de la maison Mermnche", "nomfamdrow"),
("de la maison Fey-n'Den", "nomfamdrow"),
("de la maison Zautyl", "nomfamdrow"),
("de la maison Evendar", "nomfamdrow"),
("de la maison Hlasek", "nomfamdrow"),
("de la maison Do'na", "nomfamdrow"),
("de la maison Hlan'efin", "nomfamdrow"),
("de la maison Eineld", "nomfamdrow"),
("de la maison Auneld", "nomfamdrow"),
("de la maison Maett", "nomfamdrow"),
("de la maison Tosek", "nomfamdrow"),
("de la maison Evebanche", "nomfamdrow"),
("de la maison Fey-n", "nomfamdrow"),
("de la maison Desth", "nomfamdrow"),
("de la maison Oure", "nomfamdrow"),
("de la maison Auanraduis", "nomfamdrow"),
("de la maison Helvin", "nomfamdrow"),
("de la maison Eirreneld", "nomfamdrow"),
("de la maison Hlator", "nomfamdrow"),
("de la maison Freddatyl", "nomfamdrow"),
("de la maison Arabrarvs", "nomfamdrow"),
("de la maison ZeDeep", "nomfamdrow"),
("de la maison Desar", "nomfamdrow"),
("de la maison Totor", "nomfamdrow"),
("de la maison Zelyl", "nomfamdrow"),
("de la maison Zebahel", "nomfamdrow"),
("de la maison Kiquar", "nomfamdrow"),
("de la maison Do'ssna", "nomfamdrow"),
("de la maison Goar", "nomfamdrow"),
("de la maison Evevryna", "nomfamdrow"),
("de la maison Clalesduis", "nomfamdrow"),
("de la maison Alenche", "nomfamdrow"),
("de la maison Zeund", "nomfamdrow"),
("de la maison Arkheth", "nomfamdrow"),
("de la maison Fey-rvs", "nomfamdrow"),
("de la maison Zautor", "nomfamdrow"),
("de la maison Noviir", "nomfamdrow"),
("de la maison Freleshel", "nomfamdrow"),
("de la maison Gound", "nomfamdrow"),
("de la maison Baena", "nomfamdrow"),
("de la maison Tekeni", "nomfamdrow"),
("de la maison Kite", "nomfamdrow"),
("de la maison Oun", "nomfamdrow"),
("de la maison Gona", "nomfamdrow"),
("de la maison Mynche", "nomfamdrow"),
("de la maison Gon", "nomfamdrow"),
("de la maison Riund", "nomfamdrow"),
("de la maison Rire", "nomfamdrow"),
("de la maison Fey-re", "nomfamdrow"),
("de la maison Alermar", "nomfamdrow"),
("de la maison Aleund", "nomfamdrow"),
("de la maison Zaukan", "nomfamdrow"),
("de la maison Men'eDeep", "nomfamdrow"),
("de la maison Evequar", "nomfamdrow"),
("de la maison Eisstor", "nomfamdrow"),
("de la maison Zeth", "nomfamdrow"),
("de la maison Baerhatt", "nomfamdrow"),
("de la maison Ripaduis", "nomfamdrow"),
("de la maison Topaduis", "nomfamdrow"),
("de la maison Helviduis", "nomfamdrow"),
("de la maison Freund", "nomfamdrow"),
("de la maison Teketyl", "nomfamdrow"),
("de la maison Rikan", "nomfamdrow"),
("de la maison Helvihel", "nomfamdrow"),
("de la maison Araval", "nomfamdrow"),
("de la maison Banche", "nomfamdrow"),
("de la maison Noddata", "nomfamdrow"),
("de la maison Evena", "nomfamdrow"),
("de la maison Alesek", "nomfamdrow"),
("de la maison Desre", "nomfamdrow"),
("de la maison Eiar", "nomfamdrow"),
("de la maison Do'urar", "nomfamdrow"),
("de la maison Frenche", "nomfamdrow"),
("de la maison Zetor", "nomfamdrow"),
("de la maison Clakan", "nomfamdrow"),
("de la maison Meval", "nomfamdrow"),
("de la maison Rini", "nomfamdrow"),
("de la maison Helviund", "nomfamdrow"),
("de la maison Rivir", "nomfamdrow"),
("de la maison Frelynt'ta", "nomfamdrow"),
("de la maison Hlate", "nomfamdrow"),
("de la maison Batyl", "nomfamdrow"),
("de la maison Zausek", "nomfamdrow"),
("de la maison Kear", "nomfamdrow"),
("de la maison Aussni", "nomfamdrow"),
("de la maison FreDeep", "nomfamdrow"),
("de la maison Frentt", "nomfamdrow"),
("de la maison Freval", "nomfamdrow"),
("de la maison Ban", "nomfamdrow"),
("de la maison Desvryre", "nomfamdrow"),
("de la maison GoDel'duis", "nomfamdrow"),
("de la maison Mylynt'n", "nomfamdrow"),
("de la maison Mekan", "nomfamdrow"),
("de la maison Aulynt'Den", "nomfamdrow"),
("de la maison Tohel", "nomfamdrow"),
("de la maison NoDen", "nomfamdrow"),
("de la maison Arkhevir", "nomfamdrow"),
("de la maison ToDel'tor", "nomfamdrow"),
("de la maison Arkhen'tyl", "nomfamdrow"),
("de la maison Freirytyl", "nomfamdrow"),
("de la maison Baear", "nomfamdrow"),
("de la maison Kelyl", "nomfamdrow"),
("de la maison Rilarn", "nomfamdrow"),
("de la maison MeDen", "nomfamdrow"),
("de la maison Ourreneld", "nomfamdrow"),
("de la maison Helviiryth", "nomfamdrow"),
("de la maison Aranche", "nomfamdrow"),
("de la maison Hlabrath", "nomfamdrow"),
("de la maison Do'lestt", "nomfamdrow"),
("de la maison MeriDeep", "nomfamdrow"),
("de la maison ToDen", "nomfamdrow"),
("de la maison Arkhear", "nomfamdrow"),
("de la maison Kisek", "nomfamdrow"),
("de la maison Do'bath", "nomfamdrow"),
("de la maison Meurn", "nomfamdrow"),
("de la maison Zen", "nomfamdrow"),
("de la maison Deskan", "nomfamdrow"),
("de la maison Eiund", "nomfamdrow"),
("de la maison Kivir", "nomfamdrow"),
("de la maison Clana", "nomfamdrow"),
("de la maison Zen'te", "nomfamdrow"),
("de la maison Ritt", "nomfamdrow"),
("de la maison Banneld", "nomfamdrow"),
("de la maison Rin'ett", "nomfamdrow"),
("de la maison Desrhatyl", "nomfamdrow"),
("de la maison Tekenaar", "nomfamdrow"),
("de la maison Alermkan", "nomfamdrow"),
("de la maison Maelarn", "nomfamdrow"),
("de la maison de kan", "nomfamdrow"),
("de la maison Mynani", "nomfamdrow"),
("de la maison Kiviir", "nomfamdrow"),
("de la maison Desduis", "nomfamdrow"),
("de la maison Maermna", "nomfamdrow"),
("de la maison Fey-rrenche", "nomfamdrow"),
("de la maison Kiddaval", "nomfamdrow"),
("de la maison Desn'hel", "nomfamdrow"),
("de la maison Do'ar", "nomfamdrow"),
("de la maison Helvitor", "nomfamdrow"),
("de la maison Zaunar", "nomfamdrow"),
("de la maison Toni", "nomfamdrow"),
("de la maison Auviir", "nomfamdrow"),
("de la maison Desndar", "nomfamdrow"),
("de la maison Do'anraviir", "nomfamdrow"),
("de la maison Maetor", "nomfamdrow"),
("de la maison Meth", "nomfamdrow"),
("de la maison Zaute", "nomfamdrow"),
("de la maison Noddate", "nomfamdrow"),
("de la maison Zauviir", "nomfamdrow"),
("de la maison Torvs", "nomfamdrow"),
("de la maison Goren", "nomfamdrow"),
("de la maison Fey-vrysek", "nomfamdrow"),
("de la maison Tekessvir", "nomfamdrow"),
("de la maison Helvita", "nomfamdrow"),
("de la maison Bath", "nomfamdrow"),
("de la maison Do'hel", "nomfamdrow"),
("de la maison Maenandar", "nomfamdrow"),
("de la maison Arkhena", "nomfamdrow"),
("de la maison Clavryduis", "nomfamdrow"),
("de la maison Rirvs", "nomfamdrow"),
("de la maison Kindar", "nomfamdrow"),
("de la maison Huvryni", "nomfamdrow"),
("de la maison Baeiryviir", "nomfamdrow"),
("de la maison Aunquar", "nomfamdrow"),
("de la maison Zaupakan", "nomfamdrow"),
("de la maison Ripath", "nomfamdrow"),
("de la maison Arkherirvs", "nomfamdrow"),
("de la maison Baar", "nomfamdrow"),
("de la maison Kivryar", "nomfamdrow"),
("de la maison Evekan", "nomfamdrow"),
("de la maison Maeth", "nomfamdrow"),
("de la maison Araduis", "nomfamdrow"),
("de la maison Autt", "nomfamdrow"),
("de la maison Do'te", "nomfamdrow"),
("de la maison Maeval", "nomfamdrow"),
("de la maison Fey-rhare", "nomfamdrow"),
("de la maison Kilynt're", "nomfamdrow"),
("de la maison Myfin", "nomfamdrow"),
("de la maison Maesshel", "nomfamdrow"),
("de la maison Tekervs", "nomfamdrow"),
("de la maison AraDen", "nomfamdrow"),
("de la maison Araund", "nomfamdrow"),
("de la maison Zen'endar", "nomfamdrow"),
("de la maison Meddavir", "nomfamdrow"),
("de la maison Myrmth", "nomfamdrow"),
("de la maison Desnavir", "nomfamdrow"),
("de la maison Zendar", "nomfamdrow"),
("de la maison Maervs", "nomfamdrow"),
("de la maison Baviir", "nomfamdrow"),
("de la maison Arariren", "nomfamdrow"),
("de la maison Hlath", "nomfamdrow"),
("de la maison Kibralarn", "nomfamdrow"),
("de la maison ZeDel'n", "nomfamdrow"),
("de la maison Ein'th", "nomfamdrow"),
("de la maison Araar", "nomfamdrow"),
("de la maison Helviddator", "nomfamdrow"),
("de la maison de panche", "nomfamdrow"),
("de la maison GoDeep", "nomfamdrow"),
("de la maison Goth", "nomfamdrow"),
("de la maison Baelesna", "nomfamdrow"),
("de la maison Arkhelyl", "nomfamdrow"),
("de la maison Baetyl", "nomfamdrow"),
("de la maison Zauddarvs", "nomfamdrow"),
("de la maison Gotyl", "nomfamdrow"),
("de la maison Kekan", "nomfamdrow"),
("de la maison Arani", "nomfamdrow"),
("de la maison Myren", "nomfamdrow"),
("de la maison Rilyl", "nomfamdrow"),
("de la maison Zauvryneld", "nomfamdrow"),
("de la maison Hlaurn", "nomfamdrow"),
("de la maison de tor", "nomfamdrow"),
("de la maison de urvir", "nomfamdrow"),
("de la maison Teken'rvs", "nomfamdrow"),
("de la maison Maeddaval", "nomfamdrow"),
("de la maison Fey-rmndar", "nomfamdrow"),
("de la maison Frevir", "nomfamdrow"),
("de la maison Eilarn", "nomfamdrow"),
("de la maison Teken'te", "nomfamdrow"),
("de la maison Alepafin", "nomfamdrow"),
("de la maison Auta", "nomfamdrow"),
("de la maison Arakan", "nomfamdrow"),
("de la maison Baurund", "nomfamdrow"),
("de la maison Keviir", "nomfamdrow"),
("de la maison Frequar", "nomfamdrow"),
("de la maison Do'kan", "nomfamdrow"),
("de la maison AuDel'ni", "nomfamdrow"),
("de la maison Helvifin", "nomfamdrow"),
("de la maison Desren", "nomfamdrow"),
("de la maison de rrevir", "nomfamdrow"),
("de la maison BaDel'sek", "nomfamdrow"),
("de la maison Deslyl", "nomfamdrow"),
("de la maison Maelynt'te", "nomfamdrow"),
("de la maison de val", "nomfamdrow"),
("de la maison Arkheddath", "nomfamdrow"),
("de la maison Hladuis", "nomfamdrow"),
("de la maison Toviir", "nomfamdrow"),
("de la maison Meni", "nomfamdrow"),
("de la maison Helvith", "nomfamdrow"),
("de la maison Eiquar", "nomfamdrow"),
("de la maison Desvryund", "nomfamdrow"),
("de la maison Zesek", "nomfamdrow"),
("de la maison Maebraund", "nomfamdrow"),
("de la maison Freneld", "nomfamdrow"),
("de la maison de und", "nomfamdrow"),
("de la maison Kita", "nomfamdrow"),
("de la maison Helviiryviir", "nomfamdrow"),
("de la maison Do'urth", "nomfamdrow"),
("de la maison Oulyl", "nomfamdrow"),
("de la maison Frehel", "nomfamdrow"),
("de la maison Teketa", "nomfamdrow"),
("de la maison Maelesnche", "nomfamdrow"),
("de la maison Men", "nomfamdrow"),
("de la maison Kequar", "nomfamdrow"),
("de la maison de fin", "nomfamdrow"),
("de la maison Meddaund", "nomfamdrow"),
("de la maison Claleste", "nomfamdrow"),
("de la maison Evesek", "nomfamdrow"),
("de la maison Arkheviir", "nomfamdrow"),
("de la maison Hlahel", "nomfamdrow"),
("de la maison Hlakan", "nomfamdrow"),
("de la maison Tekebath", "nomfamdrow"),
("de la maison Eini", "nomfamdrow"),
("de la maison Tekena", "nomfamdrow"),
("de la maison Ketyl", "nomfamdrow"),
("de la maison ClaDen", "nomfamdrow"),
("de la maison de hel", "nomfamdrow"),
("de la maison Eveta", "nomfamdrow"),
("de la maison Zaundar", "nomfamdrow"),
("de la maison Do'viir", "nomfamdrow"),
("de la maison Zaurvs", "nomfamdrow"),
("de la maison Zauanrata", "nomfamdrow"),
("de la maison Fressndar", "nomfamdrow"),
("de la maison Meurvir", "nomfamdrow"),
("de la maison Riren", "nomfamdrow"),
("de la maison Do'Den", "nomfamdrow"),
("de la maison Ourite", "nomfamdrow"),
("de la maison Evear", "nomfamdrow"),
("de la maison Frervs", "nomfamdrow"),
("de la maison BaDeep", "nomfamdrow"),
("de la maison Do'bare", "nomfamdrow"),
("de la maison Nound", "nomfamdrow"),
("de la maison Destyl", "nomfamdrow"),
("de la maison Desnren", "nomfamdrow"),
("de la maison Kifin", "nomfamdrow"),
("de la maison Aubatt", "nomfamdrow"),
("de la maison Barin", "nomfamdrow"),
("de la maison Aubraquar", "nomfamdrow"),
("de la maison BabaDen", "nomfamdrow"),
("de la maison Aleneld", "nomfamdrow"),
("de la maison Clairyni", "nomfamdrow"),
("de la maison Golyl", "nomfamdrow"),
("de la maison Govir", "nomfamdrow"),
("de la maison Maeund", "nomfamdrow"),
("de la maison Zauni", "nomfamdrow"),
("de la maison Aleduis", "nomfamdrow"),
("de la maison Frere", "nomfamdrow"),
("de la maison Arkheval", "nomfamdrow"),
("de la maison Desanratt", "nomfamdrow"),
("de la maison Zebrator", "nomfamdrow"),
("de la maison Maevir", "nomfamdrow"),
("de la maison Ouanraund", "nomfamdrow"),
("de la maison Baduis", "nomfamdrow"),
("de la maison Kith", "nomfamdrow"),
("de la maison Huddalarn", "nomfamdrow"),
("de la maison Gofin", "nomfamdrow"),
("de la maison Toriar", "nomfamdrow"),
("de la maison Dermsek", "nomfamdrow")

;
