INSERT INTO sentence_partials (value, class) VALUES

("de la maison Araviir", "nomfamdrow"),
("de la maison GoDel'ndar", "nomfamdrow"),
("de la maison Fey-neld", "nomfamdrow"),
("de la maison Non'duis", "nomfamdrow"),
("de la maison Mysek", "nomfamdrow"),
("de la maison Aravir", "nomfamdrow"),
("de la maison Baeund", "nomfamdrow"),
("de la maison De'th", "nomfamdrow"),
("de la maison Hlalyl", "nomfamdrow"),
("de la maison Maeduis", "nomfamdrow"),
("de la maison Zaulynt'te", "nomfamdrow"),
("de la maison Alere", "nomfamdrow"),
("de la maison Kermnche", "nomfamdrow"),
("de la maison Eiduis", "nomfamdrow"),
("de la maison OuDen", "nomfamdrow"),
("de la maison Hupatt", "nomfamdrow"),
("de la maison Tekelarn", "nomfamdrow"),
("de la maison Kervs", "nomfamdrow"),
("de la maison Rival", "nomfamdrow"),
("de la maison DeDeep", "nomfamdrow"),
("de la maison Zaunche", "nomfamdrow"),
("de la maison Meirysek", "nomfamdrow"),
("de la maison AuDeep", "nomfamdrow"),
("de la maison Freni", "nomfamdrow"),
("de la maison Rith", "nomfamdrow"),
("de la maison Ribrandar", "nomfamdrow"),
("de la maison Myund", "nomfamdrow"),
("de la maison Ken", "nomfamdrow"),
("de la maison Tekeren", "nomfamdrow"),
("de la maison Zauund", "nomfamdrow"),
("de la maison Eianrafin", "nomfamdrow"),
("de la maison Araquar", "nomfamdrow"),
("de la maison Arkheund", "nomfamdrow"),
("de la maison HuvryDen", "nomfamdrow"),
("de la maison Huneld", "nomfamdrow"),
("de la maison Clafin", "nomfamdrow"),
("de la maison Everitt", "nomfamdrow"),
("de la maison Desni", "nomfamdrow"),
("de la maison Kesek", "nomfamdrow"),
("de la maison Arator", "nomfamdrow"),
("de la maison Baneld", "nomfamdrow"),
("de la maison Tekeval", "nomfamdrow"),
("de la maison Eilyl", "nomfamdrow"),
("de la maison Evermar", "nomfamdrow"),
("de la maison Hlairyn", "nomfamdrow"),
("de la maison Bate", "nomfamdrow"),
("de la maison Helvini", "nomfamdrow"),
("de la maison Desleslyl", "nomfamdrow"),
("de la maison Noduis", "nomfamdrow"),
("de la maison Noni", "nomfamdrow"),
("de la maison Gourund", "nomfamdrow"),
("de la maison Kebran", "nomfamdrow"),
("de la maison Keni", "nomfamdrow"),
("de la maison Arkhevryta", "nomfamdrow"),
("de la maison Toth", "nomfamdrow"),
("de la maison Zeiryval", "nomfamdrow"),
("de la maison Aleddator", "nomfamdrow"),
("de la maison Keund", "nomfamdrow"),
("de la maison Nosek", "nomfamdrow"),
("de la maison Kirvs", "nomfamdrow"),
("de la maison Fey-ta", "nomfamdrow"),
("de la maison Hlaren", "nomfamdrow"),
("de la maison Tolyl", "nomfamdrow"),
("de la maison Zaulynt'und", "nomfamdrow"),
("de la maison Clarvs", "nomfamdrow"),
("de la maison Zevir", "nomfamdrow"),
("de la maison Tore", "nomfamdrow"),
("de la maison Nofin", "nomfamdrow"),
("de la maison Freduis", "nomfamdrow"),
("de la maison Frefin", "nomfamdrow"),
("de la maison Helviirynche", "nomfamdrow"),
("de la maison Do'n", "nomfamdrow"),
("de la maison Evehel", "nomfamdrow"),
("de la maison Huni", "nomfamdrow"),
("de la maison Zen'sek", "nomfamdrow"),
("de la maison Eivir", "nomfamdrow"),
("de la maison Zeren", "nomfamdrow"),
("de la maison Kilarn", "nomfamdrow"),
("de la maison Huurtor", "nomfamdrow"),
("de la maison Maendar", "nomfamdrow"),
("de la maison ToDeep", "nomfamdrow"),
("de la maison Auni", "nomfamdrow"),
("de la maison Everen", "nomfamdrow"),
("de la maison Eith", "nomfamdrow"),
("de la maison Noneld", "nomfamdrow"),
("de la maison Mebrakan", "nomfamdrow"),
("de la maison Kiirytyl", "nomfamdrow"),
("de la maison Deshel", "nomfamdrow"),
("de la maison Basste", "nomfamdrow"),
("de la maison Goriviir", "nomfamdrow"),
("de la maison Gondar", "nomfamdrow"),
("de la maison Eveviir", "nomfamdrow"),
("de la maison Hulyl", "nomfamdrow"),
("de la maison Myndar", "nomfamdrow"),
("de la maison de lynt'vir", "nomfamdrow"),
("de la maison Goval", "nomfamdrow"),
("de la maison Zena", "nomfamdrow"),
("de la maison Do'n'eren", "nomfamdrow"),
("de la maison RiDen", "nomfamdrow"),
("de la maison Claund", "nomfamdrow"),
("de la maison Clavir", "nomfamdrow"),
("de la maison Fey-Deep", "nomfamdrow"),
("de la maison Kinche", "nomfamdrow"),
("de la maison Helvitt", "nomfamdrow"),
("de la maison Fey-ntt", "nomfamdrow"),
("de la maison Gota", "nomfamdrow"),
("de la maison Mermnche", "nomfamdrow"),
("de la maison Fey-n'Den", "nomfamdrow"),
("de la maison Zautyl", "nomfamdrow"),
("de la maison Evendar", "nomfamdrow"),
("de la maison Hlasek", "nomfamdrow"),
("de la maison Do'na", "nomfamdrow"),
("de la maison Hlan'efin", "nomfamdrow"),
("de la maison Eineld", "nomfamdrow"),
("de la maison Auneld", "nomfamdrow"),
("de la maison Maett", "nomfamdrow"),
("de la maison Tosek", "nomfamdrow"),
("de la maison Evebanche", "nomfamdrow"),
("de la maison Fey-n", "nomfamdrow"),
("de la maison Desth", "nomfamdrow"),
("de la maison Oure", "nomfamdrow"),
("de la maison Auanraduis", "nomfamdrow"),
("de la maison Helvin", "nomfamdrow"),
("de la maison Eirreneld", "nomfamdrow"),
("de la maison Hlator", "nomfamdrow"),
("de la maison Freddatyl", "nomfamdrow"),
("de la maison Arabrarvs", "nomfamdrow"),
("de la maison ZeDeep", "nomfamdrow"),
("de la maison Desar", "nomfamdrow"),
("de la maison Totor", "nomfamdrow"),
("de la maison Zelyl", "nomfamdrow"),
("de la maison Zebahel", "nomfamdrow"),
("de la maison Kiquar", "nomfamdrow"),
("de la maison Do'ssna", "nomfamdrow"),
("de la maison Goar", "nomfamdrow"),
("de la maison Evevryna", "nomfamdrow"),
("de la maison Clalesduis", "nomfamdrow"),
("de la maison Alenche", "nomfamdrow"),
("de la maison Zeund", "nomfamdrow"),
("de la maison Arkheth", "nomfamdrow"),
("de la maison Fey-rvs", "nomfamdrow"),
("de la maison Zautor", "nomfamdrow"),
("de la maison Noviir", "nomfamdrow"),
("de la maison Freleshel", "nomfamdrow"),
("de la maison Gound", "nomfamdrow"),
("de la maison Baena", "nomfamdrow"),
("de la maison Tekeni", "nomfamdrow"),
("de la maison Kite", "nomfamdrow"),
("de la maison Oun", "nomfamdrow"),
("de la maison Gona", "nomfamdrow"),
("de la maison Mynche", "nomfamdrow"),
("de la maison Gon", "nomfamdrow"),
("de la maison Riund", "nomfamdrow"),
("de la maison Rire", "nomfamdrow"),
("de la maison Fey-re", "nomfamdrow"),
("de la maison Alermar", "nomfamdrow"),
("de la maison Aleund", "nomfamdrow"),
("de la maison Zaukan", "nomfamdrow"),
("de la maison Men'eDeep", "nomfamdrow"),
("de la maison Evequar", "nomfamdrow"),
("de la maison Eisstor", "nomfamdrow"),
("de la maison Zeth", "nomfamdrow"),
("de la maison Baerhatt", "nomfamdrow"),
("de la maison Ripaduis", "nomfamdrow"),
("de la maison Topaduis", "nomfamdrow"),
("de la maison Helviduis", "nomfamdrow"),
("de la maison Freund", "nomfamdrow"),
("de la maison Teketyl", "nomfamdrow"),
("de la maison Rikan", "nomfamdrow"),
("de la maison Helvihel", "nomfamdrow"),
("de la maison Araval", "nomfamdrow"),
("de la maison Banche", "nomfamdrow"),
("de la maison Noddata", "nomfamdrow"),
("de la maison Evena", "nomfamdrow"),
("de la maison Alesek", "nomfamdrow"),
("de la maison Desre", "nomfamdrow"),
("de la maison Eiar", "nomfamdrow"),
("de la maison Do'urar", "nomfamdrow"),
("de la maison Frenche", "nomfamdrow"),
("de la maison Zetor", "nomfamdrow"),
("de la maison Clakan", "nomfamdrow"),
("de la maison Meval", "nomfamdrow"),
("de la maison Rini", "nomfamdrow"),
("de la maison Helviund", "nomfamdrow"),
("de la maison Rivir", "nomfamdrow"),
("de la maison Frelynt'ta", "nomfamdrow"),
("de la maison Hlate", "nomfamdrow"),
("de la maison Batyl", "nomfamdrow"),
("de la maison Zausek", "nomfamdrow"),
("de la maison Kear", "nomfamdrow"),
("de la maison Aussni", "nomfamdrow"),
("de la maison FreDeep", "nomfamdrow"),
("de la maison Frentt", "nomfamdrow"),
("de la maison Freval", "nomfamdrow"),
("de la maison Ban", "nomfamdrow"),
("de la maison Desvryre", "nomfamdrow"),
("de la maison GoDel'duis", "nomfamdrow"),
("de la maison Mylynt'n", "nomfamdrow"),
("de la maison Mekan", "nomfamdrow"),
("de la maison Aulynt'Den", "nomfamdrow"),
("de la maison Tohel", "nomfamdrow"),
("de la maison NoDen", "nomfamdrow"),
("de la maison Arkhevir", "nomfamdrow"),
("de la maison ToDel'tor", "nomfamdrow"),
("de la maison Arkhen'tyl", "nomfamdrow"),
("de la maison Freirytyl", "nomfamdrow"),
("de la maison Baear", "nomfamdrow"),
("de la maison Kelyl", "nomfamdrow"),
("de la maison Rilarn", "nomfamdrow"),
("de la maison MeDen", "nomfamdrow"),
("de la maison Ourreneld", "nomfamdrow"),
("de la maison Helviiryth", "nomfamdrow"),
("de la maison Aranche", "nomfamdrow"),
("de la maison Hlabrath", "nomfamdrow"),
("de la maison Do'lestt", "nomfamdrow"),
("de la maison MeriDeep", "nomfamdrow"),
("de la maison ToDen", "nomfamdrow"),
("de la maison Arkhear", "nomfamdrow"),
("de la maison Kisek", "nomfamdrow"),
("de la maison Do'bath", "nomfamdrow"),
("de la maison Meurn", "nomfamdrow"),
("de la maison Zen", "nomfamdrow"),
("de la maison Deskan", "nomfamdrow"),
("de la maison Eiund", "nomfamdrow"),
("de la maison Kivir", "nomfamdrow"),
("de la maison Clana", "nomfamdrow"),
("de la maison Zen'te", "nomfamdrow"),
("de la maison Ritt", "nomfamdrow"),
("de la maison Banneld", "nomfamdrow"),
("de la maison Rin'ett", "nomfamdrow"),
("de la maison Desrhatyl", "nomfamdrow"),
("de la maison Tekenaar", "nomfamdrow"),
("de la maison Alermkan", "nomfamdrow"),
("de la maison Maelarn", "nomfamdrow"),
("de la maison de kan", "nomfamdrow"),
("de la maison Mynani", "nomfamdrow"),
("de la maison Kiviir", "nomfamdrow"),
("de la maison Desduis", "nomfamdrow"),
("de la maison Maermna", "nomfamdrow"),
("de la maison Fey-rrenche", "nomfamdrow"),
("de la maison Kiddaval", "nomfamdrow"),
("de la maison Desn'hel", "nomfamdrow"),
("de la maison Do'ar", "nomfamdrow"),
("de la maison Helvitor", "nomfamdrow"),
("de la maison Zaunar", "nomfamdrow"),
("de la maison Toni", "nomfamdrow"),
("de la maison Auviir", "nomfamdrow"),
("de la maison Desndar", "nomfamdrow"),
("de la maison Do'anraviir", "nomfamdrow"),
("de la maison Maetor", "nomfamdrow"),
("de la maison Meth", "nomfamdrow"),
("de la maison Zaute", "nomfamdrow"),
("de la maison Noddate", "nomfamdrow"),
("de la maison Zauviir", "nomfamdrow"),
("de la maison Torvs", "nomfamdrow"),
("de la maison Goren", "nomfamdrow"),
("de la maison Fey-vrysek", "nomfamdrow"),
("de la maison Tekessvir", "nomfamdrow"),
("de la maison Helvita", "nomfamdrow"),
("de la maison Bath", "nomfamdrow"),
("de la maison Do'hel", "nomfamdrow"),
("de la maison Maenandar", "nomfamdrow"),
("de la maison Arkhena", "nomfamdrow"),
("de la maison Clavryduis", "nomfamdrow"),
("de la maison Rirvs", "nomfamdrow"),
("de la maison Kindar", "nomfamdrow"),
("de la maison Huvryni", "nomfamdrow"),
("de la maison Baeiryviir", "nomfamdrow"),
("de la maison Aunquar", "nomfamdrow"),
("de la maison Zaupakan", "nomfamdrow"),
("de la maison Ripath", "nomfamdrow"),
("de la maison Arkherirvs", "nomfamdrow"),
("de la maison Baar", "nomfamdrow"),
("de la maison Kivryar", "nomfamdrow"),
("de la maison Evekan", "nomfamdrow"),
("de la maison Maeth", "nomfamdrow"),
("de la maison Araduis", "nomfamdrow"),
("de la maison Autt", "nomfamdrow"),
("de la maison Do'te", "nomfamdrow"),
("de la maison Maeval", "nomfamdrow"),
("de la maison Fey-rhare", "nomfamdrow"),
("de la maison Kilynt're", "nomfamdrow"),
("de la maison Myfin", "nomfamdrow"),
("de la maison Maesshel", "nomfamdrow"),
("de la maison Tekervs", "nomfamdrow"),
("de la maison AraDen", "nomfamdrow"),
("de la maison Araund", "nomfamdrow"),
("de la maison Zen'endar", "nomfamdrow"),
("de la maison Meddavir", "nomfamdrow"),
("de la maison Myrmth", "nomfamdrow"),
("de la maison Desnavir", "nomfamdrow"),
("de la maison Zendar", "nomfamdrow"),
("de la maison Maervs", "nomfamdrow"),
("de la maison Baviir", "nomfamdrow"),
("de la maison Arariren", "nomfamdrow"),
("de la maison Hlath", "nomfamdrow"),
("de la maison Kibralarn", "nomfamdrow"),
("de la maison ZeDel'n", "nomfamdrow"),
("de la maison Ein'th", "nomfamdrow"),
("de la maison Araar", "nomfamdrow"),
("de la maison Helviddator", "nomfamdrow"),
("de la maison de panche", "nomfamdrow"),
("de la maison GoDeep", "nomfamdrow"),
("de la maison Goth", "nomfamdrow"),
("de la maison Baelesna", "nomfamdrow"),
("de la maison Arkhelyl", "nomfamdrow"),
("de la maison Baetyl", "nomfamdrow"),
("de la maison Zauddarvs", "nomfamdrow"),
("de la maison Gotyl", "nomfamdrow"),
("de la maison Kekan", "nomfamdrow"),
("de la maison Arani", "nomfamdrow"),
("de la maison Myren", "nomfamdrow"),
("de la maison Rilyl", "nomfamdrow"),
("de la maison Zauvryneld", "nomfamdrow"),
("de la maison Hlaurn", "nomfamdrow"),
("de la maison de tor", "nomfamdrow"),
("de la maison de urvir", "nomfamdrow"),
("de la maison Teken'rvs", "nomfamdrow"),
("de la maison Maeddaval", "nomfamdrow"),
("de la maison Fey-rmndar", "nomfamdrow"),
("de la maison Frevir", "nomfamdrow"),
("de la maison Eilarn", "nomfamdrow"),
("de la maison Teken'te", "nomfamdrow"),
("de la maison Alepafin", "nomfamdrow"),
("de la maison Auta", "nomfamdrow"),
("de la maison Arakan", "nomfamdrow"),
("de la maison Baurund", "nomfamdrow"),
("de la maison Keviir", "nomfamdrow"),
("de la maison Frequar", "nomfamdrow"),
("de la maison Do'kan", "nomfamdrow"),
("de la maison AuDel'ni", "nomfamdrow"),
("de la maison Helvifin", "nomfamdrow"),
("de la maison Desren", "nomfamdrow"),
("de la maison de rrevir", "nomfamdrow"),
("de la maison BaDel'sek", "nomfamdrow"),
("de la maison Deslyl", "nomfamdrow"),
("de la maison Maelynt'te", "nomfamdrow"),
("de la maison de val", "nomfamdrow"),
("de la maison Arkheddath", "nomfamdrow"),
("de la maison Hladuis", "nomfamdrow"),
("de la maison Toviir", "nomfamdrow"),
("de la maison Meni", "nomfamdrow"),
("de la maison Helvith", "nomfamdrow"),
("de la maison Eiquar", "nomfamdrow"),
("de la maison Desvryund", "nomfamdrow"),
("de la maison Zesek", "nomfamdrow"),
("de la maison Maebraund", "nomfamdrow"),
("de la maison Freneld", "nomfamdrow"),
("de la maison de und", "nomfamdrow"),
("de la maison Kita", "nomfamdrow"),
("de la maison Helviiryviir", "nomfamdrow"),
("de la maison Do'urth", "nomfamdrow"),
("de la maison Oulyl", "nomfamdrow"),
("de la maison Frehel", "nomfamdrow"),
("de la maison Teketa", "nomfamdrow"),
("de la maison Maelesnche", "nomfamdrow"),
("de la maison Men", "nomfamdrow"),
("de la maison Kequar", "nomfamdrow"),
("de la maison de fin", "nomfamdrow"),
("de la maison Meddaund", "nomfamdrow"),
("de la maison Claleste", "nomfamdrow"),
("de la maison Evesek", "nomfamdrow"),
("de la maison Arkheviir", "nomfamdrow"),
("de la maison Hlahel", "nomfamdrow"),
("de la maison Hlakan", "nomfamdrow"),
("de la maison Tekebath", "nomfamdrow"),
("de la maison Eini", "nomfamdrow"),
("de la maison Tekena", "nomfamdrow"),
("de la maison Ketyl", "nomfamdrow"),
("de la maison ClaDen", "nomfamdrow"),
("de la maison de hel", "nomfamdrow"),
("de la maison Eveta", "nomfamdrow"),
("de la maison Zaundar", "nomfamdrow"),
("de la maison Do'viir", "nomfamdrow"),
("de la maison Zaurvs", "nomfamdrow"),
("de la maison Zauanrata", "nomfamdrow"),
("de la maison Fressndar", "nomfamdrow"),
("de la maison Meurvir", "nomfamdrow"),
("de la maison Riren", "nomfamdrow"),
("de la maison Do'Den", "nomfamdrow"),
("de la maison Ourite", "nomfamdrow"),
("de la maison Evear", "nomfamdrow"),
("de la maison Frervs", "nomfamdrow"),
("de la maison BaDeep", "nomfamdrow"),
("de la maison Do'bare", "nomfamdrow"),
("de la maison Nound", "nomfamdrow"),
("de la maison Destyl", "nomfamdrow"),
("de la maison Desnren", "nomfamdrow"),
("de la maison Kifin", "nomfamdrow"),
("de la maison Aubatt", "nomfamdrow"),
("de la maison Barin", "nomfamdrow"),
("de la maison Aubraquar", "nomfamdrow"),
("de la maison BabaDen", "nomfamdrow"),
("de la maison Aleneld", "nomfamdrow"),
("de la maison Clairyni", "nomfamdrow"),
("de la maison Golyl", "nomfamdrow"),
("de la maison Govir", "nomfamdrow"),
("de la maison Maeund", "nomfamdrow"),
("de la maison Zauni", "nomfamdrow"),
("de la maison Aleduis", "nomfamdrow"),
("de la maison Frere", "nomfamdrow"),
("de la maison Arkheval", "nomfamdrow"),
("de la maison Desanratt", "nomfamdrow"),
("de la maison Zebrator", "nomfamdrow"),
("de la maison Maevir", "nomfamdrow"),
("de la maison Ouanraund", "nomfamdrow"),
("de la maison Baduis", "nomfamdrow"),
("de la maison Kith", "nomfamdrow"),
("de la maison Huddalarn", "nomfamdrow"),
("de la maison Gofin", "nomfamdrow"),
("de la maison Toriar", "nomfamdrow"),
("de la maison Dermsek", "nomfamdrow"),

("Turaлn", "nomfamelfe"),
("Numбrer", "nomfamelfe"),
("El", "nomfamelfe"),
("Hiraton", "nomfamelfe"),
("Niment", "nomfamelfe"),
("Numamieliel", "nomfamelfe"),
("Brimor", "nomfamelfe"),
("Filul", "nomfamelfe"),
("Thandac", "nomfamelfe"),
("Narac", "nomfamelfe"),
("Amdac", "nomfamelfe"),
("Finon", "nomfamelfe"),
("Art", "nomfamelfe"),
("Torentiel", "nomfamelfe"),
("Finam", "nomfamelfe"),
("Nimanw", "nomfamelfe"),
("Ter", "nomfamelfe"),
("Amaпrл", "nomfamelfe"),
("Calбr", "nomfamelfe"),
("Glor", "nomfamelfe"),
("Palambil", "nomfamelfe"),
("Elend", "nomfamelfe"),
("Elen", "nomfamelfe"),
("Oth", "nomfamelfe"),
("Athion", "nomfamelfe"),
("Elastond", "nomfamelfe"),
("Filadrлл", "nomfamelfe"),
("Brimisial", "nomfamelfe"),
("An", "nomfamelfe"),
("Glorond", "nomfamelfe"),
("Fil", "nomfamelfe"),
("Than", "nomfamelfe"),
("Pald", "nomfamelfe"),
("Athalial", "nomfamelfe"),
("Hir", "nomfamelfe"),
("Silenial", "nomfamelfe"),
("Brim", "nomfamelfe"),
("Amastin", "nomfamelfe"),
("Elmacul", "nomfamelfe"),
("Siler", "nomfamelfe"),
("Eliлial", "nomfamelfe"),
("Finw", "nomfamelfe"),
("Tar", "nomfamelfe"),
("Glormacyлiel", "nomfamelfe"),
("Tur", "nomfamelfe"),
("Cirymeht", "nomfamelfe"),
("Andac", "nomfamelfe"),
("Hiraлn", "nomfamelfe"),
("Firdacisiel", "nomfamelfe"),
("Finilial", "nomfamelfe"),
("Brimumelel", "nomfamelfe"),
("Finambiлл", "nomfamelfe"),
("Tard", "nomfamelfe"),
("Fananatieliel", "nomfamelfe"),
("Finil", "nomfamelfe"),
("Arildillлe", "nomfamelfe"),
("Artir", "nomfamelfe"),
("Findacл", "nomfamelfe"),
("Siranatin", "nomfamelfe"),
("Nimr", "nomfamelfe"),
("Fileial", "nomfamelfe"),
("Sirel", "nomfamelfe"),
("Eдr", "nomfamelfe"),
("Filir", "nomfamelfe"),
("Cemel", "nomfamelfe"),
("Num", "nomfamelfe"),
("Linion", "nomfamelfe"),
("Fin", "nomfamelfe"),
("Fircar", "nomfamelfe"),
("Am", "nomfamelfe"),
("Loror", "nomfamelfe"),
("Numel", "nomfamelfe"),
("Filent", "nomfamelfe"),
("Hirillлл", "nomfamelfe"),
("Pal", "nomfamelfe"),
("Pelamb", "nomfamelfe"),
("Linmehtor", "nomfamelfe"),
("Numdac", "nomfamelfe"),
("Calisiel", "nomfamelfe"),
("Palбndilel", "nomfamelfe"),
("Lordac", "nomfamelfe"),
("Amer", "nomfamelfe"),
("Finacenл", "nomfamelfe"),
("Filac", "nomfamelfe"),
("Fanardielyл", "nomfamelfe"),
("Nerildior", "nomfamelfe"),
("Amonwialiл", "nomfamelfe"),
("Isendel", "nomfamelfe"),
("Finбndion", "nomfamelfe"),
("Loth", "nomfamelfe"),
("Pelandil", "nomfamelfe"),
("Thanialil", "nomfamelfe"),
("Sirir", "nomfamelfe"),
("Valel", "nomfamelfe"),
("Findyлel", "nomfamelfe"),
("Torr", "nomfamelfe"),
("Filisal", "nomfamelfe"),
("Faniлillл", "nomfamelfe"),
("Hirdaril", "nomfamelfe"),
("Filion", "nomfamelfe"),
("Artonw", "nomfamelfe"),
("Eleliл", "nomfamelfe"),
("Fanel", "nomfamelfe"),
("Lin", "nomfamelfe"),
("Calyлiel", "nomfamelfe"),
("Firul", "nomfamelfe"),
("Calion", "nomfamelfe"),
("Pelambond", "nomfamelfe"),
("Finum", "nomfamelfe"),
("Palam", "nomfamelfe"),
("Elelл", "nomfamelfe"),
("Silбreliel", "nomfamelfe"),
("Ardac", "nomfamelfe"),
("Doranw", "nomfamelfe"),
("Lalcil", "nomfamelfe"),
("Finyлil", "nomfamelfe"),
("Brimeel", "nomfamelfe"),
("Fariel", "nomfamelfe"),
("Valumer", "nomfamelfe"),
("Isieliel", "nomfamelfe"),
("Lothul", "nomfamelfe"),
("Glorildur", "nomfamelfe"),
("Dor", "nomfamelfe"),
("Hirindiel", "nomfamelfe"),
("Filen", "nomfamelfe"),
("Serur", "nomfamelfe"),
("Filardyлyл", "nomfamelfe"),
("Atil", "nomfamelfe"),
("Torul", "nomfamelfe"),
("Lothadrisyл", "nomfamelfe"),
("Silisл", "nomfamelfe"),
("Narion", "nomfamelfe"),
("Faryлiel", "nomfamelfe"),
("Terdarur", "nomfamelfe"),
("Palmacond", "nomfamelfe"),
("Amum", "nomfamelfe"),
("Narter", "nomfamelfe"),
("Terend", "nomfamelfe"),
("Farondon", "nomfamelfe"),
("Faronw", "nomfamelfe"),
("Linadr", "nomfamelfe"),
("Elaпrлe", "nomfamelfe"),
("Firr", "nomfamelfe"),
("Hirл", "nomfamelfe"),
("Aril", "nomfamelfe"),
("Terat", "nomfamelfe"),
("Amen", "nomfamelfe"),
("Othation", "nomfamelfe"),
("Fardacin", "nomfamelfe"),
("Dormac", "nomfamelfe"),
("Finandyлiл", "nomfamelfe"),
("Tardacer", "nomfamelfe"),
("Lalmehtel", "nomfamelfe"),
("Paltin", "nomfamelfe"),
("Glorбr", "nomfamelfe"),
("Finior", "nomfamelfe"),
("Torumor", "nomfamelfe"),
("Serialen", "nomfamelfe"),
("Faramлillл", "nomfamelfe"),
("Turw", "nomfamelfe"),
("Nimunъmiel", "nomfamelfe"),
("Elor", "nomfamelfe"),
("Is", "nomfamelfe"),
("Cirytond", "nomfamelfe"),
("Amandel", "nomfamelfe"),
("Ataпralielaliel", "nomfamelfe"),
("Finentelel", "nomfamelfe"),
("Artion", "nomfamelfe"),
("Firanwir", "nomfamelfe"),
("Elлe", "nomfamelfe"),
("Elent", "nomfamelfe"),
("Ciry", "nomfamelfe"),
("Pelel", "nomfamelfe"),
("Calindiel", "nomfamelfe"),
("Firil", "nomfamelfe"),
("Ciryat", "nomfamelfe"),
("Elisel", "nomfamelfe"),
("Firator", "nomfamelfe"),
("Artw", "nomfamelfe"),
("Eltialiel", "nomfamelfe"),
("Herлial", "nomfamelfe"),
("Tardariel", "nomfamelfe"),
("Athmacлл", "nomfamelfe"),
("Brimilyл", "nomfamelfe"),
("Lothacieliл", "nomfamelfe"),
("Filiel", "nomfamelfe"),
("Brimiel", "nomfamelfe"),
("Dorur", "nomfamelfe"),
("Numdin", "nomfamelfe"),
("Siradril", "nomfamelfe"),
("Arior", "nomfamelfe"),
("Ar", "nomfamelfe"),
("Isind", "nomfamelfe"),
("Finaпril", "nomfamelfe"),
("Elondil", "nomfamelfe"),
("Dormehtil", "nomfamelfe"),
("Fan", "nomfamelfe"),
("Herialel", "nomfamelfe"),
("Palmehtialil", "nomfamelfe"),
("Eldar", "nomfamelfe"),
("Ardisial", "nomfamelfe"),
("Valondil", "nomfamelfe"),
("Narбndieliл", "nomfamelfe"),
("Arлillл", "nomfamelfe"),
("Arul", "nomfamelfe"),
("Finбndon", "nomfamelfe"),
("Anardielel", "nomfamelfe"),
("Elamir", "nomfamelfe"),
("Elul", "nomfamelfe"),
("Cemild", "nomfamelfe"),
("Elin", "nomfamelfe"),
("Brimt", "nomfamelfe"),
("Farw", "nomfamelfe"),
("Finwлel", "nomfamelfe"),
("Tord", "nomfamelfe"),
("Othyлil", "nomfamelfe"),
("Calлiel", "nomfamelfe"),
("Tarindul", "nomfamelfe"),
("Firond", "nomfamelfe"),
("Terir", "nomfamelfe"),
("Glorindil", "nomfamelfe"),
("Finonw", "nomfamelfe"),
("Lorielial", "nomfamelfe"),
("Ciryildil", "nomfamelfe"),
("Isond", "nomfamelfe"),
("Elwor", "nomfamelfe"),
("Finendisal", "nomfamelfe"),
("Siraпr", "nomfamelfe"),
("Inwir", "nomfamelfe"),
("Elond", "nomfamelfe"),
("Glormac", "nomfamelfe"),
("Palil", "nomfamelfe"),
("Nimamel", "nomfamelfe"),
("Valac", "nomfamelfe"),
("Narandyлel", "nomfamelfe"),
("Gloreliл", "nomfamelfe"),
("Ath", "nomfamelfe"),
("Nerieliel", "nomfamelfe"),
("Farr", "nomfamelfe"),
("Elene", "nomfamelfe"),
("Finor", "nomfamelfe"),
("Lothcir", "nomfamelfe"),
("Lothonw", "nomfamelfe"),
("Dorw", "nomfamelfe"),
("Cemбr", "nomfamelfe"),
("Sil", "nomfamelfe"),
("Heril", "nomfamelfe"),
("Narilл", "nomfamelfe"),
("Glorumil", "nomfamelfe"),
("Herwiel", "nomfamelfe"),
("Brimul", "nomfamelfe"),
("Lothdacel", "nomfamelfe"),
("Atur", "nomfamelfe"),
("Torur", "nomfamelfe"),
("Filendion", "nomfamelfe"),
("Sililaliel", "nomfamelfe"),
("Lalcor", "nomfamelfe"),
("Elmeht", "nomfamelfe"),
("Lalend", "nomfamelfe"),
("Peliлaliel", "nomfamelfe"),
("Artmac", "nomfamelfe"),
("Nimand", "nomfamelfe"),
("Siram", "nomfamelfe"),
("Isillлyл", "nomfamelfe"),
("Anastil", "nomfamelfe"),
("Numбndyлл", "nomfamelfe"),
("Nimmehtel", "nomfamelfe"),
("Athardor", "nomfamelfe"),
("Calialiл", "nomfamelfe"),
("Taron", "nomfamelfe"),
("Nerбr", "nomfamelfe"),
("Ciryandir", "nomfamelfe"),
("Elбnd", "nomfamelfe"),
("Numt", "nomfamelfe"),
("Isin", "nomfamelfe"),
("Isyлel", "nomfamelfe"),
("Narr", "nomfamelfe"),
("Firalielyл", "nomfamelfe"),
("Finumaлn", "nomfamelfe"),
("Firaпron", "nomfamelfe"),
("Dorion", "nomfamelfe"),
("Tarul", "nomfamelfe"),
("Linard", "nomfamelfe"),
("Pelmacul", "nomfamelfe"),
("Nimyлл", "nomfamelfe"),
("Sirand", "nomfamelfe"),
("Lothaлn", "nomfamelfe"),
("Cemryлil", "nomfamelfe"),
("Ser", "nomfamelfe"),
("Lalonwin", "nomfamelfe"),
("Ciryadraliл", "nomfamelfe"),
("Thanul", "nomfamelfe"),
("Arambialial", "nomfamelfe"),
("Taratialilln", "nomfamelfe"),
("Finбndel", "nomfamelfe"),
("Thanбnd", "nomfamelfe"),
("Valin", "nomfamelfe"),
("Elion", "nomfamelfe"),
("Filambil", "nomfamelfe"),
("Hiryлл", "nomfamelfe"),
("Ciryend", "nomfamelfe"),
("Silaпril", "nomfamelfe"),
("Serar", "nomfamelfe"),
("Finaпron", "nomfamelfe"),
("Torialial", "nomfamelfe"),
("Elild", "nomfamelfe"),
("Linast", "nomfamelfe"),
("Lindaryлyл", "nomfamelfe"),
("Filunъm", "nomfamelfe"),
("Glorendior", "nomfamelfe"),
("Termeht", "nomfamelfe"),
("Toradril", "nomfamelfe"),
("Doril", "nomfamelfe"),
("Thanialal", "nomfamelfe"),
("Taril", "nomfamelfe"),
("Fanior", "nomfamelfe"),
("Fanлaliel", "nomfamelfe"),
("Filmacyлial", "nomfamelfe"),
("Numбndaлn", "nomfamelfe"),
("Lorildл", "nomfamelfe"),
("Filer", "nomfamelfe"),
("Nim", "nomfamelfe"),
("Athaпr", "nomfamelfe"),
("Lothin", "nomfamelfe"),
("Firiel", "nomfamelfe"),
("Herendлial", "nomfamelfe"),
("Teranatul", "nomfamelfe"),
("Tor", "nomfamelfe"),
("Fir", "nomfamelfe"),
("Glorandil", "nomfamelfe"),
("Filor", "nomfamelfe"),
("Othd", "nomfamelfe"),
("Nariлiл", "nomfamelfe"),
("Tarw", "nomfamelfe"),
("Atamen", "nomfamelfe"),
("Inat", "nomfamelfe"),
("Nar", "nomfamelfe"),
("Eдron", "nomfamelfe"),
("Artelл", "nomfamelfe"),
("Linum", "nomfamelfe"),
("Narielal", "nomfamelfe"),
("Sir", "nomfamelfe"),
("Thanamb", "nomfamelfe"),
("Elcaлn", "nomfamelfe"),
("Eladrin", "nomfamelfe"),
("Ciryбndлe", "nomfamelfe"),
("Her", "nomfamelfe"),
("Firat", "nomfamelfe"),
("Silind", "nomfamelfe"),
("Isil", "nomfamelfe"),
("Herildaliл", "nomfamelfe"),
("Elamalyл", "nomfamelfe"),
("Lalacil", "nomfamelfe"),
("Silonwalial", "nomfamelfe"),
("Serion", "nomfamelfe"),
("Thanmehtiel", "nomfamelfe"),
("Ciryanatilal", "nomfamelfe"),
("Elionder", "nomfamelfe"),
("Anmac", "nomfamelfe"),
("Hiren", "nomfamelfe"),
("Brimat", "nomfamelfe"),
("Caladrior", "nomfamelfe"),
("Palaпrur", "nomfamelfe"),
("Elior", "nomfamelfe"),
("Atelillл", "nomfamelfe"),
("Tardacaлn", "nomfamelfe"),
("Glorenden", "nomfamelfe"),
("Firent", "nomfamelfe"),
("Taracilil", "nomfamelfe"),
("Elard", "nomfamelfe"),
("Farлл", "nomfamelfe"),
("Lal", "nomfamelfe"),
("Finanwer", "nomfamelfe"),
("Filcлial", "nomfamelfe"),
("Neracyлe", "nomfamelfe"),
("Nimil", "nomfamelfe"),
("Isanwielл", "nomfamelfe"),
("Elum", "nomfamelfe"),
("Isrisiel", "nomfamelfe"),
("Elanwil", "nomfamelfe"),
("Nimmacil", "nomfamelfe"),
("Nimond", "nomfamelfe"),
("Firastalil", "nomfamelfe"),
("Narior", "nomfamelfe"),
("Loriлiл", "nomfamelfe"),
("Torin", "nomfamelfe"),
("Elur", "nomfamelfe"),
("Numiliл", "nomfamelfe"),
("Doraлn", "nomfamelfe"),
("Fircer", "nomfamelfe"),
("Ner", "nomfamelfe"),
("Pelumer", "nomfamelfe"),
("Naradror", "nomfamelfe"),
("Lorбr", "nomfamelfe"),
("Filamb", "nomfamelfe"),
("Nimiond", "nomfamelfe"),
("Elat", "nomfamelfe"),
("Serild", "nomfamelfe"),
("Serdacyлiл", "nomfamelfe"),
("Doren", "nomfamelfe"),
("Eдralial", "nomfamelfe"),
("Finmeht", "nomfamelfe"),
("Torcin", "nomfamelfe"),
("Elaliel", "nomfamelfe"),
("Glordacielyл", "nomfamelfe"),
("Ciryin", "nomfamelfe"),
("Cemonwur", "nomfamelfe"),
("Torat", "nomfamelfe"),
("Eдrentyлil", "nomfamelfe"),
("Faril", "nomfamelfe"),
("Cirydior", "nomfamelfe"),
("Thanildil", "nomfamelfe"),
("Ciryambar", "nomfamelfe"),
("Palt", "nomfamelfe"),
("Filil", "nomfamelfe"),
("Fanandion", "nomfamelfe"),
("Torend", "nomfamelfe"),
("Filtielen", "nomfamelfe"),
("Neronwer", "nomfamelfe"),
("Teren", "nomfamelfe"),
("Linialillл", "nomfamelfe"),
("Numenial", "nomfamelfe"),
("Herdin", "nomfamelfe"),
("Firielis", "nomfamelfe"),
("Caliondin", "nomfamelfe"),
("Ataлn", "nomfamelfe"),
("Dorбr", "nomfamelfe"),
("Eldaciel", "nomfamelfe"),
("Dorunъm", "nomfamelfe"),
("Hird", "nomfamelfe"),
("Atanaten", "nomfamelfe"),
("Glorunъmil", "nomfamelfe"),
("Amw", "nomfamelfe"),
("Loronw", "nomfamelfe"),
("Attil", "nomfamelfe"),
("Teraлn", "nomfamelfe"),
("Elatir", "nomfamelfe"),
("Serandin", "nomfamelfe"),
("Artior", "nomfamelfe"),
("Turadrur", "nomfamelfe"),
("Lalardilal", "nomfamelfe"),
("Heren", "nomfamelfe"),
("Filл", "nomfamelfe"),
("Inanwon", "nomfamelfe"),
("Thanir", "nomfamelfe"),
("Finaciлiel", "nomfamelfe"),
("Serw", "nomfamelfe"),
("Artaлn", "nomfamelfe"),
("Firacisл", "nomfamelfe"),
("Eдren", "nomfamelfe"),
("Sildaron", "nomfamelfe"),
("Narбndyлen", "nomfamelfe"),
("Amion", "nomfamelfe"),
("Arandior", "nomfamelfe"),
("Nariond", "nomfamelfe"),
("Othiale", "nomfamelfe"),
("Serбrialel", "nomfamelfe"),
("Fanardil", "nomfamelfe"),
("Lorril", "nomfamelfe"),
("Herandor", "nomfamelfe"),
("Firild", "nomfamelfe"),
("Tarл", "nomfamelfe"),
("Eliel", "nomfamelfe"),
("Lalialaliel", "nomfamelfe"),
("Thanw", "nomfamelfe"),
("Terar", "nomfamelfe"),
("Thanбr", "nomfamelfe"),
("Silonwul", "nomfamelfe"),
("Doram", "nomfamelfe"),
("Calamb", "nomfamelfe"),
("Filaпreniel", "nomfamelfe"),
("Hercielyл", "nomfamelfe"),
("Isandor", "nomfamelfe"),
("Cemastaлn", "nomfamelfe"),
("Terunъmul", "nomfamelfe"),
("Eдrond", "nomfamelfe"),
("Arealiel", "nomfamelfe"),
("Arten", "nomfamelfe"),
("Paliond", "nomfamelfe"),
("Atharden", "nomfamelfe"),
("Heratond", "nomfamelfe"),
("Inul", "nomfamelfe"),
("Othril", "nomfamelfe"),
("Isardion", "nomfamelfe"),
("Valaster", "nomfamelfe"),
("Farondyлл", "nomfamelfe"),
("Lalonder", "nomfamelfe"),
("At", "nomfamelfe"),
("Eliлyл", "nomfamelfe"),
("Elambior", "nomfamelfe"),
("Dorambel", "nomfamelfe"),
("Lothunъmon", "nomfamelfe"),
("Serir", "nomfamelfe"),
("Ciryond", "nomfamelfe"),
("Valatiлiel", "nomfamelfe"),
("Cemлyл", "nomfamelfe"),
("Eдrior", "nomfamelfe"),
("Palamb", "nomfamelfe"),
("Findaralal", "nomfamelfe"),
("Cemden", "nomfamelfe"),
("Finmehtil", "nomfamelfe"),
("Finбndilel", "nomfamelfe"),
("Lalanwil", "nomfamelfe"),
("Peldin", "nomfamelfe"),
("Cemt", "nomfamelfe"),
("Anir", "nomfamelfe"),
("Nimion", "nomfamelfe"),
("Dorild", "nomfamelfe"),
("Elunъmin", "nomfamelfe"),
("Cem", "nomfamelfe"),
("Findar", "nomfamelfe"),
("Teram", "nomfamelfe"),
("Atind", "nomfamelfe"),
("Isildion", "nomfamelfe"),
("Valaпr", "nomfamelfe"),
("Numбrillлial", "nomfamelfe"),
("Herwлal", "nomfamelfe"),
("Cemac", "nomfamelfe"),
("Finiel", "nomfamelfe"),
("Inen", "nomfamelfe"),
("Amisen", "nomfamelfe"),
("Lor", "nomfamelfe"),
("Finisil", "nomfamelfe"),
("Ciryamb", "nomfamelfe"),
("Palmac", "nomfamelfe"),
("Eldacialiel", "nomfamelfe"),
("Taryлal", "nomfamelfe"),
("Elonw", "nomfamelfe"),
("Anon", "nomfamelfe"),
("Brimond", "nomfamelfe"),
("Linamb", "nomfamelfe"),
("Anard", "nomfamelfe"),
("Tarent", "nomfamelfe"),
("Nimл", "nomfamelfe"),
("Terdel", "nomfamelfe"),
("Sirent", "nomfamelfe"),
("Cirymehten", "nomfamelfe"),
("Thanindion", "nomfamelfe"),
("Elбr", "nomfamelfe"),
("Filand", "nomfamelfe"),
("Eltul", "nomfamelfe"),
("Elaпrialial", "nomfamelfe"),
("Turmacieliл", "nomfamelfe"),
("Silard", "nomfamelfe"),
("Atiлiel", "nomfamelfe"),
("Thant", "nomfamelfe"),
("Inil", "nomfamelfe"),
("Elacilis", "nomfamelfe"),
("Hirind", "nomfamelfe"),
("Anбrar", "nomfamelfe"),
("Atondil", "nomfamelfe"),
("Amildiel", "nomfamelfe"),
("Herunъmil", "nomfamelfe"),
("Finast", "nomfamelfe"),
("Hiriel", "nomfamelfe"),
("Tarild", "nomfamelfe"),
("Amam", "nomfamelfe"),
("Ciryenten", "nomfamelfe"),
("Lothcon", "nomfamelfe"),
("Anast", "nomfamelfe"),
("Eleyл", "nomfamelfe"),
("Valonw", "nomfamelfe"),
("Lothast", "nomfamelfe"),
("Filend", "nomfamelfe"),
("Laldac", "nomfamelfe"),
("Othil", "nomfamelfe"),

("add", "nomgnome1"),
("arum", "nomgnome1"),
("baer", "nomgnome1"),
("bar", "nomgnome1"),
("callad", "nomgnome1"),
("chik", "nomgnome1"),
("dal", "nomgnome1"),
("din", "nomgnome1"),
("eaus", "nomgnome1"),
("enn", "nomgnome1"),
("erf", "nomgnome1"),
("faer", "nomgnome1"),
("fen", "nomgnome1"),
("flan", "nomgnome1"),
("gaer", "nomgnome1"),
("gar", "nomgnome1"),
("hed", "nomgnome1"),
("herl", "nomgnome1"),
("ien", "nomgnome1"),
("jan", "nomgnome1"),
("kaer", "nomgnome1"),
("len", "nomgnome1"),
("lun", "nomgnome1"),
("mikk", "nomgnome1"),
("neb", "nomgnome1"),
("oaen", "nomgnome1"),
("ow", "nomgnome1"),
("pall", "nomgnome1"),
("pin", "nomgnome1"),
("raer", "nomgnome1"),
("ras", "nomgnome1"),
("seg", "nomgnome1"),
("skor", "nomgnome1"),
("tikk", "nomgnome1"),
("uran", "nomgnome1"),
("urd", "nomgnome1"),
("van", "nomgnome1"),
("var", "nomgnome1"),
("wann", "nomgnome1"),
("wed", "nomgnome1"),

("Acier", "nomgnome2"),
("Appeleur", "nomgnome2"),
("Argent", "nomgnome2"),
("Bière", "nomgnome2"),
("Blaireau", "nomgnome2"),
("Boucle", "nomgnome2"),
("Brille", "nomgnome2"),
("Buveur", "nomgnome2"),
("Cape", "nomgnome2"),
("Cendre", "nomgnome2"),
("Coeur", "nomgnome2"),
("Colline", "nomgnome2"),
("Eclair", "nomgnome2"),
("Enjambeur", "nomgnome2"),
("Errant", "nomgnome2"),
("Fantâme", "nomgnome2"),
("Faux-pas", "nomgnome2"),
("Fer", "nomgnome2"),
("Gemme", "nomgnome2"),
("Honneur", "nomgnome2"),
("Leste", "nomgnome2"),
("Lune", "nomgnome2"),
("Main", "nomgnome2"),
("Oeil", "nomgnome2"),
("Ombre", "nomgnome2"),
("Or", "nomgnome2"),
("Os", "nomgnome2"),
("Paresse", "nomgnome2"),
("Peau", "nomgnome2"),
("PÃ©llant", "nomgnome2"),
("Petit", "nomgnome2"),
("Pied", "nomgnome2"),
("Pierre", "nomgnome2"),
("Rapide", "nomgnome2"),
("Renard", "nomgnome2"),
("Rieur", "nomgnome2"),
("Ruse", "nomgnome2"),
("Sauvage", "nomgnome2"),
("Soleil", "nomgnome2"),
("Soupir", "nomgnome2"),
("Terre", "nomgnome2")

;
